var QUESTION_DARE = [
"F001$Hát to một đoạn bài hát yêu thích.",
"F002$Nhảy một điệu nhảy 'tủ' của bạn.",
"F003$Kể một câu chuyện cười.",
"F004$Uống một ly nước với tốc độ nhanh nhất có thể.",
"F005$Cười thật lớn trong 30 giây.",
"F006$Nói ba điều bạn thích về người bên trái bạn.",
"F007$Đổi điện thoại với người bên phải bạn trong 5 phút.",
"F008$Kể lại một câu chuyện ma bạn từng nghe.",
"F009$Đặt tay lên mũi và nói 'Tôi yêu bạn' vớ mọi người.",
"F010$Nhắm mắt và chỉ vào một người bất kỳ trong phòng.",
"F011$Đi lại như vịt trong 1 phút.",
"F012$Đứng lên và hô to 'Tôi là siêu anh hùng!'",
"F013$Làm một động tác thể dục nào đó.",
"F014$Cắt một trái chanh và ăn nó.",
"F015$Viết tên của người bạn đang thích lên một tờ giấy.",
"F016$Đứng lên và tạo dáng như một bức tượng.",
"F017$Dùng chân để viết tên của một người trong nhóm.",
"F018$Kể một câu chuyện cười mà không được cười.",
"F019$Hô to một câu nói 'truyền cảm hứng' của bạn.",
"F020$Giả vờ là một con vật và nói chuyện với người bên cạnh.",
"F021$Dùng tay để vẽ một bức tranh 'tuyệt vời' của một người trong nhóm.",
"F022$Đổi một món đồ bất kỳ trên người với người bên trái bạn.",
"F023$Hát một bài hát mà không được mở miệng.",
"F024$Làm một động tác 'ngớ ngẩn' mà không ai trong nhóm biết.",
"F025$Đi lùi lại trong 30 giây.",
"F026$Dùng điện thoại để chụp một bức ảnh 'tự sướng' hài hước.",
"F027$Kể một câu chuyện 'ma' mà không được nhắm mắt.",
"F028$Nói 'Tôi yêu bạn' với một người lạ qua điện thoại.",
"F029$Nhảy một điệu nhảy ngẫu nhiên trong 15 giây.",
"F030$Dùng một món đồ bất kỳ để làm 'mũ' và đội nó lên đầu.",

"E001$Cởi một chiếc tất và đi vòng quanh phòng.",
"E002$Nhắn tin cho người lạ và hỏi 'Bạn có muốn đi ăn kem không?'",
"E003$Lấy son hoặc kem đánh răng bôi lên mặt.",
"E004$Giả vờ bị đau bụng và rên rỉ trong 1 phút.",
"E005$Kể một câu chuyện về lần bạn bị 'quê' nhất.",
"E006$Gọi điện cho bố mẹ và nói 'Con yêu bố mẹ rất nhiều!'",
"E007$Lấy một vật bất kỳ trên bàn và diễn tả nó bằng điệu bộ.",
"E008$Hôn một bức ảnh trên điện thoại.",
"E009$Đăng một status ngớ ngẩn lên mạng xã hội.",
"E010$Tỏ tình với một người nào đó trong phòng.",
"E011$Nói chuyện với người bên cạnh bạn bằng giọng trẻ con.",
"E012$Làm một động tác giống con mèo.",
"E013$Đứng lên và kể một câu chuyện ma mà bạn tự bịa ra.",
"E014$Chơi trò 'oẳn tù tì' với một người bạn bất kỳ.",
"E015$Đeo tai nghe và hát một bài hát bất kỳ.",
"E016$Hôn lên má của người ngồi bên trái bạn.",
"E017$Gọi điện cho một người bạn và nói 'Tôi yêu bạn rất nhiều!'",
"E018$Nhảy một điệu nhảy 'lạ' trong 30 giây.",
"E019$Hát một bài hát mà bạn 'ghét' nhất.",
"E020$Lấy một chiếc thìa và 'diễn' lại một cảnh phim lãng mạn.",
"E021$Cười 'khổng lồ' trong 15 giây.",
"E022$Đứng lên và nói 'Tôi là người đẹp trai nhất/xinh gái nhất!'",
"E023$Chấp nhận một 'Dare' từ người bên trái bạn.",
"E024$Lấy một vật bất kỳ trên bàn và 'kể' một câu chuyện về nó.",
"E025$Nhắn tin cho người lạ và hỏi 'Bạn có muốn 'làm quen' với tôi không?'",
"E026$Hôn một bức ảnh trên điện thoại.",
"E027$Đóng một mắt và 'hát' một bài hát.",
"E028$Lấy một chiếc đệm và 'ôm' nó như người yêu của bạn.",
"E029$Nói chuyện bằng 'giọng' trẻ con trong 1 phút.",
"E030$Để người ngồi bên phải bạn 'vẽ' một hình lên trán bạn.",

"D001$Mò mẫm và tìm một vật bất kỳ trong phòng.",
"D002$Đeo một chiếc khẩu trang, giả vờ là ca sĩ nổi tiếng và hát.",
"D003$Chấp nhận một 'Dare' từ người khác.",
"D004$Lấy một chiếc dép và đi vòng quanh phòng.",
"D005$Dùng tay để vẽ chân dung của người bên phải bạn.",
"D006$Nhảy 'Twerk' trong 30 giây.",
"D007$Diễn tả một loài động vật bằng điệu bộ, cử chỉ.",
"D008$Uống một ly nước có pha chút muối.",
"D009$Giả vờ là một người nổi tiếng và nói chuyện với người bên cạnh.",
"D010$Nhắn tin cho một người bạn và hỏi: 'Bạn có thích tớ không?'",
"D011$Bịt mắt và sờ vào tay một người nào đó.",
"D012$Thử hôn lên một vật vô tri vô giác trong phòng.",
"D013$Lấy một vật bất kỳ trong túi xách và diễn tả nó.",
"D014$Giả vờ 'ngủ gật' trong 30 giây.",
"D015$Đeo một chiếc tất lên tay và nói chuyện với nó.",
"D016$Hôn lên má của người ngồi đối diện bạn.",
"D017$Gọi điện cho một người lạ và nói 'Tôi yêu bạn!'",
"D018$Nhảy một điệu nhảy 'lạ' và 'kỳ quái' trong 30 giây.",
"D019$Hát một bài hát mà bạn 'thích' nhưng không được mở miệng.",
"D020$Lấy một chiếc thìa và 'diễn' lại một cảnh phim 'hành động'.",
"D021$Cười 'khổng lồ' trong 15 giây.",
"D022$Đứng lên và nói 'Tôi là người đẹp trai nhất/xinh gái nhất!'",
"D023$Chấp nhận một 'Dare' từ người ngồi bên trái bạn.",
"D024$Lấy một vật bất kỳ trên bàn và 'kể' một câu chuyện 'ma' về nó.",
"D025$Nhắn tin cho người lạ và hỏi 'Bạn có muốn 'làm quen' với tôi không?'",
"D026$Hôn một bức ảnh trên điện thoại.",
"D027$Đóng một mắt và 'hát' một bài hát.",
"D028$Lấy một chiếc đệm và 'ôm' nó như người yêu của bạn.",
"D029$Nói chuyện bằng 'giọng' trẻ con trong 1 phút.",
"D030$Để người ngồi bên phải bạn 'vẽ' một hình lên trán bạn.",

"C001$Hôn lên má người bên phải bạn.",
"C002$Nhắn tin cho người bạn thân nhất và nói 'Tôi yêu bạn!'.",
"C003$Diễn lại một cảnh 'nhạy cảm' trong phim.",
"C004$Cởi một chiếc áo khoác hoặc một chiếc tất.",
"C005$Ngậm một chiếc thìa và nhảy múa.",
"C006$Giả vờ là một con vật và nói chuyện với người bên cạnh.",
"C007$Lấy một chiếc đệm và dùng nó làm gối.",
"C008$Đeo một chiếc khẩu trang, đi lại và chào tất cả mọi người.",
"C009$Hôn lên má người mà bạn cảm thấy 'hấp dẫn' nhất.",
"C010$Đổi một món đồ trang sức với người bên trái bạn.",
"C011$Nhắm mắt và nói về 'tình dục' trong 30 giây.",
"C012$Viết một lời 'hứa' lên tay bạn.",
"C013$Nhắn tin cho một người bạn khác giới và nói 'Tôi muốn ngủ với bạn!'.",
"C014$Cầm một chiếc dép và hát một bài hát nào đó.",
"C015$Cởi một chiếc giày và dùng nó để gõ lên bàn.",
"C016$Hôn lên má của người ngồi đối diện bạn.",
"C017$Gọi điện cho một người lạ và nói 'Tôi yêu bạn!'",
"C018$Nhảy một điệu nhảy 'lạ' và 'kỳ quái' trong 30 giây.",
"C019$Hát một bài hát mà bạn 'thích' nhưng không được mở miệng.",
"C020$Lấy một chiếc thìa và 'diễn' lại một cảnh phim 'hành động'.",
"C021$Cười 'khổng lồ' trong 15 giây.",
"C022$Đứng lên và nói 'Tôi là người đẹp trai nhất/xinh gái nhất!'",
"C023$Chấp nhận một 'Dare' từ người ngồi bên trái bạn.",
"C024$Lấy một vật bất kỳ trên bàn và 'kể' một câu chuyện 'ma' về nó.",
"C025$Nhắn tin cho người lạ và hỏi 'Bạn có muốn 'làm quen' với tôi không?'",
"C026$Hôn một bức ảnh trên điện thoại.",
"C027$Đóng một mắt và 'hát' một bài hát.",
"C028$Lấy một chiếc đệm và 'ôm' nó như người yêu của bạn.",
"C029$Nói chuyện bằng 'giọng' trẻ con trong 1 phút.",
"C030$Để người ngồi bên phải bạn 'vẽ' một hình lên trán bạn.",

"B001$Cởi một món đồ nào đó trên người.",
"B002$Gọi điện cho một người lạ và nói 'Tôi yêu bạn!'.",
"B003$Hôn lên môi của người bên trái bạn.",
"B004$Uống một ly nước 'bẩn'.",
"B005$Lấy một vật bất kỳ và dùng nó để 'đánh' vào một người nào đó.",
"B006$Nhảy múa trong 1 phút.",
"B007$Hôn lên một vật 'kỳ quái' trong phòng.",
"B008$Nhắn tin cho một người lạ trên mạng xã hội và nói 'Bạn có muốn 'quan hệ' với tôi không?'.",
"B009$Cởi một chiếc áo.",
"B010$Đứng lên và nói 'Tôi yêu bạn!'.",
"B011$Đặt tay lên một người nào đó và nói 'Tôi muốn 'quan hệ' với bạn!'.",
"B012$Hôn lên một vật 'bất tiện' trong phòng.",
"B013$Lấy một chiếc dép và dùng nó để 'đập' vào một người nào đó.",
"B014$Nhảy múa 'cực đoan'.",
"B015$Đứng lên và nói 'Tôi yêu người yêu của bạn!'.",
"B016$Hôn lên má của người ngồi đối diện bạn.",
"B017$Gọi điện cho một người lạ và nói 'Tôi yêu bạn!'",
"B018$Nhảy một điệu nhảy 'lạ' và 'kỳ quái' trong 30 giây.",
"B019$Hát một bài hát mà bạn 'thích' nhưng không được mở miệng.",
"B020$Lấy một chiếc thìa và 'diễn' lại một cảnh phim 'hành động'.",
"B021$Cười 'khổng lồ' trong 15 giây.",
"B022$Đứng lên và nói 'Tôi là người đẹp trai nhất/xinh gái nhất!'",
"B023$Chấp nhận một 'Dare' từ người ngồi bên trái bạn.",
"B024$Lấy một vật bất kỳ trên bàn và 'kể' một câu chuyện 'ma' về nó.",
"B025$Nhắn tin cho người lạ và hỏi 'Bạn có muốn 'làm quen' với tôi không?'",
"B026$Hôn một bức ảnh trên điện thoại.",
"B027$Đóng một mắt và 'hát' một bài hát.",
"B028$Lấy một chiếc đệm và 'ôm' nó như người yêu của bạn.",
"B029$Nói chuyện bằng 'giọng' trẻ con trong 1 phút.",
"B030$Để người ngồi bên phải bạn 'vẽ' một hình lên trán bạn.",

"A001$Hôn lên bất cứ bộ phận nào trên mặt của người ngồi đối diện bạn.",
"A002$Nhắn tin cho người mà bạn đang 'crush' và hỏi họ về 'bí mật' của họ.",
"A003$Đeo một chiếc tất lên tay và nói 'Tôi muốn hôn bạn' với người bạn thân nhất.",
"A004$Hôn một vật 'nhạy cảm' trong phòng.",
"A005$Đổi một món đồ lót với người bên phải bạn.",
"A006$Đứng lên và nhảy một điệu nhảy 'gợi cảm' trong 30 giây.",
"A007$Gọi điện cho mẹ bạn và nói 'Con yêu một người trong nhóm này!'",
"A008$Để người ngồi bên trái bạn 'vuốt ve' bạn trong 10 giây.",
"A009$Nhắn tin cho người lạ và hỏi 'Bạn có muốn 'làm tình' với tôi không?'",
"A010$Cởi một chiếc áo và trao cho người bạn thích.",
"A011$Để người ngồi bên phải bạn viết một từ 'nhạy cảm' lên trán bạn.",
"A012$Hôn lên bất cứ đâu trên cơ thể của người ngồi đối diện bạn.",
"A013$Nhảy một điệu nhảy 'lạ' với một người bạn khác giới.",
"A014$Hôn lên môi của người ngồi đối diện bạn.",
"A015$Để người ngồi bên trái bạn 'vuốt ve' bạn trong 30 giây.",
"A016$Hôn lên má của người ngồi đối diện bạn.",
"A017$Gọi điện cho một người lạ và nói 'Tôi yêu bạn!'",
"A018$Nhảy một điệu nhảy 'lạ' và 'kỳ quái' trong 30 giây.",
"A019$Hát một bài hát mà bạn 'thích' nhưng không được mở miệng.",
"A020$Lấy một chiếc thìa và 'diễn' lại một cảnh phim 'hành động'.",
"A021$Cười 'khổng lồ' trong 15 giây.",
"A022$Đứng lên và nói 'Tôi là người đẹp trai nhất/xinh gái nhất!'",
"A023$Chấp nhận một 'Dare' từ người ngồi bên trái bạn.",
"A024$Lấy một vật bất kỳ trên bàn và 'kể' một câu chuyện 'ma' về nó.",
"A025$Nhắn tin cho người lạ và hỏi 'Bạn có muốn 'làm quen' với tôi không?'",
"A026$Hôn một bức ảnh trên điện thoại.",
"A027$Đóng một mắt và 'hát' một bài hát.",
"A028$Lấy một chiếc đệm và 'ôm' nó như người yêu của bạn.",
"A029$Nói chuyện bằng 'giọng' trẻ con trong 1 phút.",
"A030$Để người ngồi bên phải bạn 'vẽ' một hình lên trán bạn.",

"SX.X$Miêu tả cảm xúc khi bị đụng vào chỗ đó bởi người khác khác giới mà bạn có tình cảm lúc đang có 'ham muốn' !!!",
"SX.X$Hãy để lộ vai và một bên dây áo lót của bạn, thời gian một vòng chơi---Nam miễn!!!",
"SX.X$Kéo áo bản thân lên cao trong thời gian một vòng chơi, không để lộ ngực!!!",
"SX.X$Nhắm mắt, dùng cả một bàn tay chạm hoàn toàn vào chỗ đó đến khi kết thúc lượt người kế tiếp, được phép ngồi và che!!!",
"SX.X$Hãy cắn móng tay ngón trỏ và bày ra bộ mặt dâm đảng nhất---Nam miễn!!!",
"SX.X$Hãy chọn một bạn nữ tát đít bản thân bạn một cú thật mạnh---Nữ miễn!!!",
"SX.X$Hãy vuốt ve một bạn nam có trong vòng với bộ mặt thật thỏa mãn---Nữ Miễn!!!"
]