let QUESTION_TRUTH = [
"F001$Món ăn bạn thích nhất là gì?",
"F002$Nếu có thể trở thành một loài động vật, bạn muốn là con gì?",
"F003$Bạn có tin vào ma quỷ không?",
"F004$Đồ vật giá trị nhất bạn đang sở hữu là gì?",
"F005$Bộ phim hoạt hình yêu thích nhất của bạn là gì?",
"F006$Bạn có bao giờ nói dối bố mẹ chưa?",
"F007$Bạn đã từng thích thầm một ai đó chưa?",
"F008$Kỉ niệm đáng nhớ nhất thời thơ ấu của bạn là gì?",
"F009$Nếu trúng số độc đắc, bạn sẽ làm gì đầu tiên?",
"F010$Bài hát yêu thích nhất của bạn là gì?",
"F011$Bạn có một biệt danh nào 'ngớ ngẩn' không?",
"F012$Bạn có thể ngủ ở bất cứ đâu không?",
"F013$Điều bạn tự hào nhất về bản thân là gì?",
"F014$Bạn sợ con vật gì nhất?",
"F015$Bạn có từng ăn cắp vặt gì chưa?",
"F016$Nếu bạn có thể sở hữu một siêu năng lực, bạn muốn có năng lực gì?",
"F017$Bạn đã bao giờ thử ăn một món ăn 'kinh dị' nào đó chưa?",
"F018$Bạn có một thói quen 'lạ' nào khi ở một mình không?",
"F019$Điều gì khiến bạn 'xấu hổ' nhất khi ở cùng người lạ?",
"F020$Bạn có tin vào người ngoài hành tinh không?",
"F021$Bộ phim hoặc cuốn sách khiến bạn khóc nhiều nhất là gì?",
"F022$Bạn có một bí mật 'ngớ ngẩn' nào liên quan đến idol của mình không?",
"F023$Nếu bạn là một nhân vật hoạt hình, bạn muốn là ai?",
"F024$Bạn có bao giờ 'tưởng tượng' mình là một ca sĩ/diễn viên nổi tiếng chưa?",
"F025$Bạn có thể kể về lần đầu tiên đi máy bay/tàu hỏa của mình không?",
"F026$Bạn có thể nói một từ 'bí mật' mà chỉ bạn và người thân biết không?",
"F027$Món đồ 'vô dụng' nhất bạn từng mua là gì?",
"F028$Điều bạn làm khi 'cực kỳ' buồn chán là gì?",
"F029$Bạn đã bao giờ 'thích' một người vì tính cách hài hước của họ chưa?",
"F030$Nếu có thể quay ngược thời gian 1 giờ, bạn sẽ làm gì?",

"E001$Bạn đã bao giờ làm một việc gì đó mà sau này hối hận chưa?",
"E002$Bạn có một bí mật nào đó mà bạn chưa từng kể cho ai không?",
"E003$Điều bạn ghét nhất ở bản thân là gì?",
"E004$Bạn có bao giờ lén lút đọc tin nhắn của người khác chưa?",
"E005$Ai là người bạn tin tưởng nhất trên đời?",
"E006$Bạn có nghĩ mình là một người tốt không?",
"E007$Nếu có thể thay đổi một điều trong quá khứ, bạn sẽ thay đổi điều gì?",
"E008$Bạn có từng 'phản bội' một người bạn thân chưa?",
"E009$Lần cuối cùng bạn khóc là khi nào và vì sao?",
"E010$Bạn có bao giờ giả vờ ốm để được nghỉ học/nghỉ làm chưa?",
"E011$Bạn có thể sống thiếu điện thoại trong 1 tháng không?",
"E012$Điều lãng mạn nhất bạn từng làm cho ai đó là gì?",
"E013$Bạn đã từng 'crush' người yêu của bạn thân chưa?",
"E014$Bạn có bao giờ ghen tị với ai đó chưa?",
"E015$Bạn có thể kể về lần đầu tiên hôn của mình không?",
"E016$Bạn đã bao giờ 'thích' một người vì tính cách 'ngược ngạo' của họ chưa?",
"E017$Bạn có một thói quen 'ngớ ngẩn' nào khi ở một mình không?",
"E018$Bạn có tin vào tình yêu sét đánh không?",
"E019$Điều bạn 'hối hận' nhất khi còn đi học là gì?",
"E020$Bạn có một 'bí mật' nào đó về gia đình bạn mà bạn chưa từng kể cho ai không?",
"E021$Lần cuối cùng bạn 'khóc' vì một người khác là khi nào?",
"E022$Bạn có bao giờ 'lén lút' ăn vụng nửa đêm chưa?",
"E023$Nếu có thể 'đổi' một điều về bản thân, bạn sẽ đổi điều gì?",
"E024$Bạn có bao giờ 'tưởng tượng' mình là một người khác không?",
"E025$Bạn đã từng 'đặt' tên cho một vật vô tri vô giác chưa?",
"E026$Bạn có bao giờ 'ăn trộm' đồ ăn của người khác chưa?",
"E027$Bạn có một 'cách' để 'giấu' cảm xúc của mình không?",
"E028$Bạn có bao giờ 'làm' một điều gì đó vì 'tò mò' không?",
"E029$Bạn nghĩ gì về 'tình yêu' qua mạng xã hội?",
"E030$Bạn có một 'nguyên tắc' sống nào không bao giờ phá vỡ không?",

"D001$Bạn đã bao giờ lừa dối người yêu chưa?",
"D002$Bạn có bao giờ bịa chuyện về một ai đó để được nổi tiếng chưa?",
"D003$Bạn đã từng bị say xỉn và làm một việc gì đó điên rồ chưa?",
"D004$Bạn có một sở thích nào 'kỳ lạ' không?",
"D005$Bạn nghĩ gì về việc 'ngoại tình'?",
"D006$Bạn đã từng 'dụ dỗ' một người nào đó để đạt được mục đích của mình chưa?",
"D007$Bạn đã từng 'thả thính' cùng lúc nhiều người chưa?",
"D008$Bạn đã từng gửi nhầm tin nhắn 'nhạy cảm' chưa?",
"D009$Bạn có một nỗi sợ hãi nào 'kỳ cục' không?",
"D010$Bạn có từng giả vờ mình là người khác trên mạng xã hội chưa?",
"D011$Bạn có bao giờ 'nói xấu' bạn bè của mình chưa?",
"D012$Nếu được chọn, bạn muốn làm người yêu của ai trong nhóm này?",
"D013$Bạn có thích một người đã có người yêu chưa?",
"D014$Bạn có thể kể về lần đầu tiên 'tò mò' về giới tính không?",
"D015$Bạn có từng 'ăn cắp' bản quyền của ai đó chưa?",
"D016$Bạn đã bao giờ 'thích' một người vì 'gu' thời trang của họ chưa?",
"D017$Bạn có một thói quen 'kỳ lạ' nào liên quan đến giấc ngủ không?",
"D018$Bạn có tin vào lời nguyền không?",
"D019$Lần bạn 'phạm' một điều luật 'quan trọng' là khi nào?",
"D020$Bạn có một bí mật 'lớn' nào về người yêu cũ của bạn không?",
"D021$Lần cuối cùng bạn 'ghen' với một người khác là khi nào?",
"D022$Bạn có bao giờ 'lén lút' nghe lén cuộc trò chuyện của người khác chưa?",
"D023$Nếu được 'đổi' một điều về cuộc đời mình, bạn sẽ đổi điều gì?",
"D024$Bạn có bao giờ 'tưởng tượng' mình là một người 'tồi tệ' không?",
"D025$Bạn đã từng 'bị' lừa đảo qua mạng xã hội chưa?",
"D026$Bạn có bao giờ 'nói xấu' một người nào đó ngay trước mặt họ chưa?",
"D027$Bạn có một 'cách' để 'được lòng' người khác không?",
"D028$Bạn có bao giờ 'thích' một người mà bạn biết họ có 'vấn đề' chưa?",
"D029$Bạn nghĩ gì về 'tình yêu' qua 'tình một đêm'?",
"D030$Bạn có một 'nguyên tắc' nào về tình yêu không bao giờ phá vỡ không?",

"C001$Bạn đã từng làm 'chuyện ấy' với ai chưa?",
"C002$Bạn có bao giờ 'tự sướng' chưa?",
"C003$Bạn có một bí mật 'đen tối' nào chưa từng kể cho ai không?",
"C004$Bạn nghĩ gì về tình yêu 'một đêm'?",
"C005$Bạn có một 'ám ảnh' nào đó về tình dục không?",
"C006$Bạn có bao giờ 'lên giường' với bạn thân của mình chưa?",
"C007$Bạn có bao giờ bị 'đánh cắp' một nụ hôn chưa?",
"C008$Bạn đã từng ngủ với một người lạ chưa?",
"C009$Bạn có thể kể về lần đầu tiên 'quan hệ' của mình không?",
"C010$Bạn có bao giờ dùng 'sextoys' chưa?",
"C011$Bạn có bao giờ 'thủ dâm' ở nơi công cộng chưa?",
"C012$Bạn đã từng có ý nghĩ 'ngoài luồng' với người yêu của bạn chưa?",
"C013$Bạn có nghĩ 'tình dục' là điều quan trọng trong tình yêu không?",
"C014$Bạn đã từng quay 'clip' nhạy cảm chưa?",
"C015$Bạn có bao giờ xem 'phim đen' chưa?",
"C016$Bạn đã bao giờ 'thích' một người vì 'gu' âm nhạc của họ chưa?",
"C017$Bạn có một thói quen 'kỳ lạ' nào liên quan đến tình yêu không?",
"C018$Bạn có tin vào lời nguyền không?",
"C019$Lần bạn 'phạm' một điều luật 'quan trọng' là khi nào?",
"C020$Bạn có một bí mật 'lớn' nào về người yêu cũ của bạn không?",
"C021$Lần cuối cùng bạn 'ghen' với một người khác là khi nào?",
"C022$Bạn có bao giờ 'lén lút' nghe lén cuộc trò chuyện của người khác chưa?",
"C023$Nếu được 'đổi' một điều về cuộc đời mình, bạn sẽ đổi điều gì?",
"C024$Bạn có bao giờ 'tưởng tượng' mình là một người 'tồi tệ' không?",
"C025$Bạn đã từng 'bị' lừa đảo qua mạng xã hội chưa?",
"C026$Bạn có bao giờ 'nói xấu' một người nào đó ngay trước mặt họ chưa?",
"C027$Bạn có một 'cách' để 'được lòng' người khác không?",
"C028$Bạn có bao giờ 'thích' một người mà bạn biết họ có 'vấn đề' chưa?",
"C029$Bạn nghĩ gì về 'tình yêu' qua 'tình một đêm'?",
"C030$Bạn có một 'nguyên tắc' nào về tình yêu không bao giờ phá vỡ không?",

"B001$Bạn đã từng 'tự tử' chưa?",
"B002$Bạn đã từng 'đánh cắp' một vật gì đó có giá trị lớn chưa?",
"B003$Bạn đã từng 'phá hoại' một mối quan hệ nào đó của người khác chưa?",
"B004$Bạn có một 'bí mật' nào đó liên quan đến pháp luật không?",
"B005$Bạn có bao giờ 'quan hệ' với người cùng giới chưa?",
"B006$Bạn có bao giờ 'cực đoan' trong tình dục chưa?",
"B007$Bạn có một 'khao khát' tình dục kỳ lạ nào không?",
"B008$Bạn đã từng 'quan hệ' với người 'có quan hệ' với bạn bè của bạn chưa?",
"B009$Bạn có thể kể về lần 'bị lạm dụng' chưa?",
"B010$Bạn có bao giờ 'bán dâm' chưa?",
"B011$Bạn đã từng 'ăn cắp' tiền của bố mẹ chưa?",
"B012$Bạn có bao giờ 'tống tiền' người khác chưa?",
"B013$Bạn có một 'khuất tất' nào đó về quá khứ không?",
"B014$Bạn có bao giờ 'tấn công' một người nào đó chưa?",
"B015$Bạn có bao giờ 'cưỡng hiếp' ai đó chưa?",
"B016$Bạn đã bao giờ 'thích' một người vì 'gu' âm nhạc của họ chưa?",
"B017$Bạn có một thói quen 'kỳ lạ' nào liên quan đến tình yêu không?",
"B018$Bạn có tin vào lời nguyền không?",
"B019$Lần bạn 'phạm' một điều luật 'quan trọng' là khi nào?",
"B020$Bạn có một bí mật 'lớn' nào về người yêu cũ của bạn không?",
"B021$Lần cuối cùng bạn 'ghen' với một người khác là khi nào?",
"B022$Bạn có bao giờ 'lén lút' nghe lén cuộc trò chuyện của người khác chưa?",
"B023$Nếu được 'đổi' một điều về cuộc đời mình, bạn sẽ đổi điều gì?",
"B024$Bạn có bao giờ 'tưởng tượng' mình là một người 'tồi tệ' không?",
"B025$Bạn đã từng 'bị' lừa đảo qua mạng xã hội chưa?",
"B026$Bạn có bao giờ 'nói xấu' một người nào đó ngay trước mặt họ chưa?",
"B027$Bạn có một 'cách' để 'được lòng' người khác không?",
"B028$Bạn có bao giờ 'thích' một người mà bạn biết họ có 'vấn đề' chưa?",
"B029$Bạn nghĩ gì về 'tình yêu' qua 'tình một đêm'?",
"B030$Bạn có một 'nguyên tắc' nào về tình yêu không bao giờ phá vỡ không?",

"A001$Bạn đã bao giờ 'thích' một người vì mùi hương cơ thể của họ chưa?",
"A002$Món đồ lót màu gì bạn thấy 'sexy' nhất?",
"A003$Bạn nghĩ nụ hôn ở đâu trên cơ thể là 'điên' nhất?",
"A004$Lần cuối cùng bạn 'thèm khát' ai đó là khi nào?",
"A005$Nếu được tặng một bộ đồ ngủ, bạn muốn nó 'thiếu vải' hay 'kín đáo'?",
"A006$Bạn có 'khao khát' được hôn một người nào đó trong nhóm này không?",
"A007$Đâu là vị trí 'thích' của bạn khi ngủ cùng người ấy?",
"A008$Bạn có nghĩ mình 'hấp dẫn' không?",
"A009$Bạn có một 'cách' để quyến rũ người khác không?",
"A010$Bạn thích được 'vuốt ve' ở đâu nhất?",
"A011$Bạn có nghĩ mình là một người 'tốt' trên giường không?",
"A012$Bạn thích được 'thủ thỉ' điều gì vào tai?",
"A013$Bạn có một 'bí mật' nào đó về tình dục mà bạn chưa kể cho ai không?",
"A014$Bạn nghĩ mình có thể 'chiều' người yêu đến mức nào?",
"A015$Đâu là điều 'tồi tệ' nhất bạn đã làm trong một mối quan hệ?",
"A016$Bạn đã bao giờ 'thích' một người vì 'gu' âm nhạc của họ chưa?",
"A017$Bạn có một thói quen 'kỳ lạ' nào liên quan đến tình yêu không?",
"A018$Bạn có tin vào lời nguyền không?",
"A019$Lần bạn 'phạm' một điều luật 'quan trọng' là khi nào?",
"A020$Bạn có một bí mật 'lớn' nào về người yêu cũ của bạn không?",
"A021$Lần cuối cùng bạn 'ghen' với một người khác là khi nào?",
"A022$Bạn có bao giờ 'lén lút' nghe lén cuộc trò chuyện của người khác chưa?",
"A023$Nếu được 'đổi' một điều về cuộc đời mình, bạn sẽ đổi điều gì?",
"A024$Bạn có bao giờ 'tưởng tượng' mình là một người 'tồi tệ' không?",
"A025$Bạn đã từng 'bị' lừa đảo qua mạng xã hội chưa?",
"A026$Bạn có bao giờ 'nói xấu' một người nào đó ngay trước mặt họ chưa?",
"A027$Bạn có một 'cách' để 'được lòng' người khác không?",
"A028$Bạn có bao giờ 'thích' một người mà bạn biết họ có 'vấn đề' chưa?",
"A029$Bạn nghĩ gì về 'tình yêu' qua 'tình một đêm'?",
"A030$Bạn có một 'nguyên tắc' nào về tình yêu không bao giờ phá vỡ không?",

"SX.X$Màu áo lótnữ mà bạn đang mặc?---Nam miễn!!!",
"SX.X$Bạn có cạo lông chỗ đó không?---Nam miễn!!!",
"SX.X$Bạn cảm nhận chỗ đó của bạn có mùi như thế nào?---Nam miễn!!!",
"SX.X$Tên người mà bạn mơ thấy khi mộng tinh?!!!",
"SX.X$Bạn bắt đầu cảm thấy muốn làm chuyện đó với người mình thích vào năm nào?!!!",
"SX.X$Cây hàng của bạn dài bao nhiêu?---Nữ miễn!!!",
"SX.X$Bạn thấy phần lông chỗ đó của bạn như nào?---Nữ miễn!!!",
"SX.X$Bạn đã bao giờ tò mò về tinh dịch của bản thân có vị gì chưa?!!!",
]