let QUESTION_TRUTH = [
"F001$Món ăn bạn thích nhất là gì?",
"F002$Nếu có thể trở thành một loài động vật, bạn muốn là con gì?",
"F003$Bạn có tin vào ma quỷ không?",
"F004$Đồ vật giá trị nhất bạn đang sở hữu là gì?",
"F005$Bộ phim hoạt hình yêu thích nhất của bạn là gì?",
"F006$Bạn có bao giờ nói dối bố mẹ chưa?",
"F007$Bạn đã từng thích thầm một ai đó chưa?",
"F008$Kỉ niệm đáng nhớ nhất thời thơ ấu của bạn là gì?",
"F009$Nếu trúng số độc đắc, bạn sẽ làm gì đầu tiên?",
"F010$Bài hát yêu thích nhất của bạn là gì?",
"F011$Bạn có một biệt danh nào 'ngớ ngẩn' không?",
"F012$Bạn có thể ngủ ở bất cứ đâu không?",
"F013$Điều bạn tự hào nhất về bản thân là gì?",
"F014$Bạn sợ con vật gì nhất?",
"F015$Bạn có từng ăn cắp vặt gì chưa?",
"F016$Nếu bạn có thể sở hữu một siêu năng lực, bạn muốn có năng lực gì?",
"F017$Bạn đã bao giờ thử ăn một món ăn 'kinh dị' nào đó chưa?",
"F018$Bạn có một thói quen 'lạ' nào khi ở một mình không?",
"F019$Điều gì khiến bạn 'xấu hổ' nhất khi ở cùng người lạ?",
"F020$Bạn có tin vào người ngoài hành tinh không?",
"F021$Bộ phim hoặc cuốn sách khiến bạn khóc nhiều nhất là gì?",
"F022$Bạn có một bí mật 'ngớ ngẩn' nào liên quan đến idol của mình không?",
"F023$Nếu bạn là một nhân vật hoạt hình, bạn muốn là ai?",
"F024$Bạn có bao giờ 'tưởng tượng' mình là một ca sĩ/diễn viên nổi tiếng chưa?",
"F025$Bạn có thể kể về lần đầu tiên đi máy bay/tàu hỏa của mình không?",
"F026$Bạn có thể nói một từ 'bí mật' mà chỉ bạn và người thân biết không?",
"F027$Món đồ 'vô dụng' nhất bạn từng mua là gì?",
"F028$Điều bạn làm khi 'cực kỳ' buồn chán là gì?",
"F029$Bạn đã bao giờ 'thích' một người vì tính cách hài hước của họ chưa?",
"F030$Nếu có thể quay ngược thời gian 1 giờ, bạn sẽ làm gì?",
"F031$Kể tên một thói quen xấu nhất mà bạn đang cố gắng từ bỏ.",
"F032$Nếu có thể quay ngược thời gian, bạn muốn thay đổi điều gì trong quá khứ?",
"F033$Điều gì khiến bạn cảm thấy tự hào nhất về bản thân?",
"F034$Kể một bí mật thời thơ ấu mà chưa ai biết.",
"F035$Mô tả 3 từ về con người thật của bạn mà người khác có thể không nhận ra.",
"F036$Nếu có thể sống trong một bộ phim, bạn sẽ chọn bộ phim nào và vào vai ai?",
"F037$Bạn đã bao giờ nói dối để thoát khỏi một rắc rối lớn chưa?",
"F038$Kể về lần đầu tiên bạn say rượu (nếu có).",
"F039$Nếu bạn có một triệu đô la, bạn sẽ làm gì với nó?",
"F040$Điều gì là thử thách lớn nhất bạn từng đối mặt?",
"F041$Nếu phải đánh đổi một điều gì đó quan trọng nhất để có được tiền bạc, bạn sẽ đánh đổi điều gì?",
"F042$Bạn đã bao giờ dùng tiền để giải quyết một rắc rối lớn chưa?",
"F043$Bạn có sẵn sàng 'đạp lên' người khác để đạt được mục tiêu của mình không?",
"F044$Điều gì là động lực lớn nhất của bạn trong công việc?",
"F045$Kể về một lần bạn tiêu tiền một cách vô nghĩa nhưng lại cảm thấy rất hài lòng.",
"F046$Nếu bạn có thể tàng hình trong một ngày, điều đầu tiên bạn sẽ làm là gì?",
"F047$Loại nhạc nào khiến bạn xấu hổ nhất khi nghe?",
"F048$Bạn thích nhất điều gì ở bản thân mình?",
"F049$Điều gì khiến bạn khó chịu nhất?",
"F050$Lần cuối cùng bạn nói dối là khi nào?",
"F051$Lần đầu tiên bạn bị 'thất tình' là khi nào?",
"F052$Điều gì ở một người bạn khiến bạn khó chịu nhất nhưng bạn vẫn chấp nhận được?",
"F053$Nếu phải chọn một người trong nhóm làm 'em bé' để chăm sóc trong một ngày, bạn sẽ chọn ai?",
"F054$Bạn đã bao giờ nói 'tôi yêu bạn' với một người bạn thân chưa?",
"F055$Điều gì ở người khác mà bạn ngưỡng mộ nhất?",
"F056$Bạn đã từng 'để ý' đến một người bạn thân chưa?",
"F057$Điều gì bạn nghĩ là 'tệ' nhất khi bạn có một người bạn trai/bạn gái?",
"F058$Món quà ý nghĩa nhất bạn từng nhận được từ một người bạn là gì?",
"F059$Điều gì khiến bạn cảm thấy an toàn và thoải mái khi ở bên cạnh ai đó?",
"F060$Nếu có thể trở lại quá khứ để thay đổi một điều về mối quan hệ của bạn với một người nào đó, bạn sẽ thay đổi điều gì?",
"F061$Nếu có thể biến một thứ bất kỳ thành món tráng miệng, bạn sẽ chọn cái gì?",
"F062$Bạn đã từng làm đổ thứ gì vào người khác một cách 'cực kỳ xấu hổ' chưa?",
"F063$Nếu phải mặc một bộ trang phục của nhân vật hoạt hình trong một tuần, bạn sẽ chọn ai?",
"F064$Bạn đã bao giờ nhặt được tiền trên đường chưa? Nếu có, bạn làm gì với nó?",
"F065$Bạn có từng 'lục lọi' điện thoại của ai đó chưa?",
"F066$Lần bạn 'quê độ' nhất trước mặt người lạ là khi nào?",
"F067$Món đồ nào trong nhà bạn 'quý' đến mức không ai được đụng vào?",
"F068$Bạn đã bao giờ phải lòng một nhân vật hư cấu chưa?",
"F069$Nếu có một người theo dõi bạn cả ngày và ghi lại mọi việc bạn làm, họ sẽ thấy điều gì bất ngờ nhất?",
"F070$Bạn có từng ngủ gật ở một nơi công cộng nào đó chưa?",
"F071$Điều gì khiến bạn cười nhiều nhất?",
"F072$Bạn đã bao giờ nói dối rằng mình đã xem một bộ phim hoặc một cuốn sách nào đó để 'hợp' với mọi người chưa?",
"F073$Bạn thích tắm vòi sen hay tắm bồn hơn?",
"F074$Nếu bạn có thể 'tăng tốc' thời gian khi làm một việc, đó là việc gì?",
"F075$Bạn sẽ làm gì nếu bạn đột nhiên trở thành người duy nhất trên Trái Đất?",
"F076$Nếu có thể đổi chỗ cho một người nổi tiếng bất kỳ trong một ngày, bạn sẽ chọn ai?",
"F077$Kỹ năng vô dụng nhất mà bạn từng học là gì?",
"F078$Nếu tiền không phải là vấn đề, bạn sẽ làm gì mỗi ngày?",
"F079$Bạn thích bị mắc kẹt ở một hòn đảo hoang với ai nhất trong nhóm chúng ta?",
"F080$Nếu bạn có thể 'tẩy não' một kỷ niệm trong quá khứ, bạn sẽ xóa đi kỷ niệm nào?",
"F081$Bí mật nào bạn chưa từng kể với ai trong nhóm?",
"F082$Nếu một ngày bạn thức dậy và có thể nói chuyện với động vật, con vật đầu tiên bạn muốn trò chuyện là gì?",
"F083$Bạn có 'tật xấu' nào mà bạn bè không biết không?",
"F084$Nếu được chọn một siêu năng lực, bạn sẽ chọn gì và dùng nó để làm gì?",
"F085$Bạn có từng 'sáng tác' ra một câu chuyện hoặc một lời nói dối chỉ để thoát khỏi rắc rối chưa?",
"F086$Lần cuối cùng bạn khóc là vì chuyện gì?",
"F087$Bạn thích nhận quà bất ngờ hay được hỏi trước khi mua hơn?",
"F088$Bạn có tin vào ma quỷ hay những điều siêu nhiên không?",
"F089$Bạn cảm thấy 'tội lỗi' nhất khi làm điều gì?",
"F090$Điều gì khiến bạn cảm thấy tự tin và hạnh phúc nhất về bản thân?",
"F091$Món ăn mà bạn ghét nhất khi còn nhỏ là gì?",
"F092$Lần đầu tiên bạn bị bố mẹ phạt nặng nhất là vì chuyện gì?",
"F093$Kỷ niệm ngốc nghếch nhất mà bạn còn nhớ khi học cấp 1 là gì?",
"F094$Bạn đã từng ăn trộm thứ gì chưa? Nếu có, đó là thứ gì?",
"F095$Bạn có từng ước mơ trở thành một nghề nghiệp 'bất bình thường' nào không? (ví dụ: người nhặt rác vũ trụ, thám tử chó...)",
"F096$Bài hát 'tủ' mà bạn hay hát thầm khi tắm lúc còn bé là gì?",
"F097$Món đồ chơi mà bạn quý nhất khi còn nhỏ là gì?",
"F098$Bạn đã bao giờ giả vờ ốm để được nghỉ học chưa?",
"F099$Bạn có từng viết thư tình hoặc có 'crush' với ai đó ở trường chưa?",
"F100$Bạn còn giữ lại món đồ nào từ thời thơ ấu đến bây giờ không?",
`__Lười_Biếng_.School.F$Tại sao bạn thường xuyên báo cáo sai số lượng bài tập về nhà đã hoàn thành với giáo viên?`,
`____None_____.School.F$School.$Bạn có cố tình "loại bỏ" chi tiết quan trọng khi kể lại một sự kiện xấu của bạn mình cho người khác không?`,
`__Phàm_Ăn____.School.F$"Ở đâu" là nơi bí mật nhất bạn từng ăn vụng trong giờ học?`,
`____None_____.School.F$School.$Điều gì là lời bào chữa tệ nhất bạn từng dùng để trốn tiết học thể dục?`,
`____Đố_Kị____.School.F$Bạn có bao giờ âm thầm ước bạn mình bị điểm kém chỉ vì họ giỏi hơn bạn ở môn đó chưa?`,
`____None_____.School.F$Bạn đã "thay thế" sự thật bằng một câu chuyện tưởng tượng như thế nào để gây ấn tượng với người bạn thích?`,
`__Kiêu_Ngạo__.School.F$Tại sao bạn luôn cảm thấy mình xứng đáng nhận được điểm cao hơn những gì giáo viên đưa ra?`,
`____None_____.School.F$Ai là người bạn đã "kết hợp" lời nói dối của mình để tạo ra một câu chuyện thuyết phục hơn với phụ huynh?`,
`__Lười_Biếng_.School.F$Bạn đã "đảo ngược" lịch trình học tập của mình như thế nào (ngủ vào ban ngày và thức khuya) để trốn tránh việc phải làm bài?`,
`____None_____.School.F$Bạn có "tận dụng" danh sách nghỉ ốm của lớp để cố tình đi học muộn mà không bị phạt không?`,
`__Tham_Lam___.School.F$Điều gì bạn đã hứa hẹn với một người bạn để họ nhường cho bạn món quà của trường?`,
`____None_____.School.F$Khi nào bạn đã "sửa đổi" ngày tháng trên một tài liệu học tập để làm giả việc nộp bài đúng hạn?`,
`__Lười_Biếng_.School.F$Bạn có cho rằng việc chỉ nhìn trộm bài bạn khi giáo viên quay lưng không phải là gian lận không?`,
`____None_____.School.F$Ai là người bạn đã "loại bỏ" khỏi nhóm học tập chỉ vì họ không đồng ý với ý kiến của bạn?`,
`__Phàm_Ăn____.School.F$Tại sao bạn lại nói dối giáo viên là bị dị ứng để không phải chia sẻ đồ ăn vặt của mình?`,
`____None_____.School.F$Bạn đã "thích nghi" với việc bị phát hiện quay cóp bằng cách nào để không bị mời phụ huynh?`,
`____Đố_Kị____.School.F$Ở đâu bạn từng cố ý làm hỏng đồ dùng học tập của người mà bạn không thích?`,
`__Lười_Biếng_.Social.F$Tại sao bạn thường xuyên tương tác với bài đăng mà không đọc nội dung, chỉ để tỏ ra mình là người quan tâm?`,
`____None_____.Social.F$Bạn có "loại bỏ" những bức ảnh "xấu" của bạn bè khỏi một album nhóm chỉ để mình bạn trông đẹp nhất không?`,
`__Phàm_Ăn____.Social.F$Điều gì là món ăn bạn đã chụp ảnh giả vờ ăn để đăng bài, nhưng thực chất bạn không hề thích nó?`,
`____None_____.Social.F$"Ở đâu" là nơi bạn chụp ảnh check-in sang trọng nhất mà bạn chỉ đi ngang qua?`,
`____Đố_Kị____.Social.F$Bạn có bao giờ hủy theo dõi một người bạn chỉ vì ghen tị với cuộc sống hoàn hảo của họ trên mạng không?`,
`____None_____.Social.F$Bạn đã "thay thế" ảnh đại diện của mình bằng ảnh người khác như thế nào để trò chuyện với người lạ?`,
`__Kiêu_Ngạo__.Social.F$Ai là người bạn đã chặn (block) ngay lập tức vì họ dám bình luận chê bai về phong cách của bạn?`,
`____None_____.Social.F$Khi nào bạn đã "kết hợp" hai bức ảnh cũ lại với nhau và đăng lên để giả vờ đang đi du lịch?`,
`__Lười_Biếng_.Social.F$Bạn đã "đảo ngược" thời gian đăng bài như thế nào để tạo ấn tượng rằng bạn đã hoàn thành một công việc sớm?`,
`____None_____.Social.F$Bạn có "tận dụng" tính năng thăm dò ý kiến để tìm kiếm lời khen cho bản thân thay vì hỏi ý kiến thật không?`,
`__Tham_Lam___.Social.F$Điều gì là thứ bạn đã mua (dù không cần) chỉ vì nó được influencer yêu thích đăng tải?`,
`____None_____.Social.F$Tại sao bạn lại "sửa đổi" thông tin nghề nghiệp của mình trên hồ sơ mạng xã hội để trông quan trọng hơn?`,
`__Lười_Biếng_.Social.F$Bạn có thừa nhận rằng ít nhất 50% những bài chia sẻ về quan điểm của bạn là copy từ người khác không?`,
`____None_____.Social.F$Ai là người mà bạn đã "loại bỏ" khỏi danh sách bạn bè chỉ vì họ có ít người theo dõi?`,
`__Phàm_Ăn____.Social.F$Ở đâu là nơi bạn từng sử dụng WiFi miễn phí của hàng xóm để xem video ăn uống ngấu nghiến vào đêm khuya?`,
`____None_____.Social.F$Bạn đã "thích nghi" bằng cách nào để tạo ra một hồ sơ "ảo" thứ hai để theo dõi người mà bạn không dám theo dõi bằng tài khoản thật?`,
`____Đố_Kị____.Social.F$Điều gì là lời nói cay độc nhất bạn từng viết trong tin nhắn riêng về một người bạn nổi tiếng trên mạng?`,
`__Lười_Biếng_.Funk.F$Tại sao bạn thường trì hoãn việc bắt đầu một dự án mới vì sợ thất bại?`,
`____None_____.Funk.F$Bạn có "loại bỏ" bằng chứng về một sự kiện xấu hổ trong quá khứ vì sợ bị người khác phát hiện không?`,
`__Phàm_Ăn____.Funk.F$Điều gì là món ăn bạn đã từ chối thử vì bạn quá sợ kết cấu hoặc mùi vị lạ của nó?`,
`____None_____.Funk.F$"Ở đâu" là nơi bạn từng giả vờ bị lạc chỉ vì sợ hãi khi phải nói chuyện với người lạ?`,
`____Đố_Kị____.Funk.F$Bạn có cố tình tránh nói chuyện với một người thành công vì sợ phải đối diện với sự kém cỏi của bản thân không?`,
`____None_____.Funk.F$Bạn đã "thay thế" sự thật về nỗi sợ của mình bằng một câu chuyện hài hước như thế nào để tránh bị trêu chọc?`,
`__Kiêu_Ngạo__.Funk.F$Ai là người bạn đã cố tình nói về những thành công của mình trước mặt để che giấu sự sợ hãi về việc bị đánh giá thấp?`,
`____None_____.Funk.F$Khi nào bạn đã "kết hợp" hai lời nói dối lại với nhau để che giấu nỗi sợ độ cao khi đi tàu lượn siêu tốc?`,
`__Lười_Biếng_.Funk.F$Bạn đã "đảo ngược" lịch trình của mình như thế nào (ví dụ: thức trắng đêm) vì sợ gặp ác mộng?`,
`____None_____.Funk.F$Bạn có "tận dụng" câu chuyện về nỗi sợ hãi của mình để thao túng người khác phải đưa ra quyết định có lợi cho bạn không?`,
`__Tham_Lam___.Funk.F$Điều gì là thứ bạn đã mua (dù không cần) vì sợ bị bạn bè/người thân bỏ rơi nếu bạn không có nó?`,
`____None_____.Funk.F$Tại sao bạn lại "sửa đổi" phản ứng của mình trước nỗi sợ để nó trông có vẻ dũng cảm hơn khi bị quay phim?`,
`__Lười_Biếng_.Funk.F$Bạn có thừa nhận rằng bạn thường nói dối về việc bạn đã làm việc chăm chỉ chỉ vì sợ bị phạt vì thiếu nỗ lực không?`,
`____None_____.Funk.F$Ai là người bạn đã cố tình "loại bỏ" khỏi danh sách bạn bè vì sợ rằng họ sẽ tiết lộ một bí mật đáng xấu hổ của bạn?`,
`__Phàm_Ăn____.Funk.F$Khi nào là lần gần nhất bạn ăn quá nhiều để xoa dịu nỗi sợ hãi về một điều gì đó sắp xảy ra?`,
`____None_____.Funk.F$Bạn đã "thích nghi" bằng cách nào để luôn mang theo một vật may mắn vì sợ những điều xui xẻo?`,
`____Đố_Kị____.Funk.F$"Ở đâu" là nơi bạn từng cố ý nói dối về thành công của người khác vì sợ bị họ vượt mặt?`,


"E001$Bạn đã bao giờ làm một việc gì đó mà sau này hối hận chưa?",
"E002$Điều bạn ghét nhất ở bản thân là gì?",
"E003$Điều lãng mạn nhất bạn từng làm cho ai đó là gì?",
"E004$Bạn có bao giờ 'lén lút' ăn vụng nửa đêm chưa?",
"E005$Nếu có thể 'đổi' một điều về bản thân, bạn sẽ đổi điều gì?",
"E006$Bạn đã từng 'đặt' tên cho một vật vô tri vô giác chưa?",
"E007$Bạn có từng 'quay cóp' trong thi cử chưa?",
"E008$Nếu có thể thay đổi một điều về ngoại hình, bạn sẽ thay đổi điều gì?",
"E009$Kể về kế hoạch của bạn trong 5 năm tới.",
"E010$Điều gì là mục tiêu lớn nhất bạn muốn đạt được trước tuổi 30?",
"E011$Kể về một lần bạn đã lừa dối ai đó một cách có chủ ý.",
"E012$Nếu bạn chỉ còn một tháng để sống, bạn sẽ làm gì?",
"E013$Điều gì là suy nghĩ bí ẩn nhất mà bạn từng có?",
"E014$Bạn đã bao giờ thử ăn một loại thực phẩm kỳ lạ nào đó chỉ để cho vui chưa?",
"E015$Bạn đã bao giờ thử 'dám' làm một việc gì đó mà sau này phải hối hận chưa?",
"E016$Bạn có từng ăn trộm thứ gì chưa? Nếu có, đó là thứ gì?",
"E017$Bạn có từng 'lục lọi' điện thoại của ai đó chưa?",
"E018$Nếu có thể 'tăng tốc' thời gian khi làm một việc, đó là việc gì?",
"E019$Nếu một ngày bạn thức dậy và có thể nói chuyện với động vật, con vật đầu tiên bạn muốn trò chuyện là gì?",
"E020$Lần đầu tiên bạn bị bố mẹ phạt nặng nhất là vì chuyện gì?",
"E021$Bạn có thể sống thiếu điện thoại trong 1 tháng không?",
"E022$Bạn có thể kể về lần đầu tiên hôn của mình không?",
"E023$Bạn có một thói quen 'ngớ ngẩn' nào khi ở một mình không?",
"E024$Bạn có tin vào tình yêu sét đánh không?",
"E025$Bạn có một 'cách' để 'giấu' cảm xúc của mình không?",
"E026$Bạn có bao giờ 'làm' một điều gì đó vì 'tò mò' không?",
"E027$Bạn nghĩ gì về 'tình yêu' qua mạng xã hội?",
"E028$Nếu không bị giới hạn về tiền bạc, bạn sẽ làm công việc gì?",
"E029$Bạn có tin vào “định mệnh” không?",
"E030$Bạn có muốn kết hôn và có con không?",
"E031$Bạn có một 'tật xấu' nào mà bạn bè không biết không?",
"E032$Bạn còn giữ lại món đồ nào từ thời thơ ấu đến bây giờ không?",
"E033$Bạn có tin vào ma quỷ hay những điều siêu nhiên không?",
"E034$Nếu tiền không phải là vấn đề, bạn sẽ làm gì mỗi ngày?",
"E035$Bạn có một nỗi sợ hãi 'vô lý' nào không?",
"E036$Món quà 'vô dụng' nhất mà bạn từng nhận được là gì?",
"E037$Lần cuối cùng bạn khóc là khi nào và vì sao?",
"E038$Lần cuối cùng bạn khóc là vì chuyện gì?",
"E039$Điều bạn 'hối hận' nhất khi còn đi học là gì?",
"E040$Nếu được chọn một nghề nghiệp khác, bạn muốn làm gì?",
"E041$Kể về một kỷ niệm đáng nhớ nhất thời đi học.",
"E042$Điều gì là áp lực lớn nhất của bạn trong công việc/học tập hiện tại?",
"E043$Nếu có thể biến một thứ bất kỳ thành món tráng miệng, bạn sẽ chọn cái gì?",
"E044$Nếu được chọn một siêu năng lực, bạn sẽ chọn gì và dùng nó để làm gì?",
"E045$Kỷ niệm ngốc nghếch nhất mà bạn còn nhớ khi học cấp 1 là gì?",
"E046$Nếu có thể thay đổi một điều trong quá khứ, bạn sẽ thay đổi điều gì?",
"E047$Nếu có thể 'tẩy não' một kỷ niệm trong quá khứ, bạn sẽ xóa đi kỷ niệm nào?",
"E048$Kể về một kỷ niệm thời thơ ấu khiến bạn cảm thấy bị ám ảnh đến bây giờ.",
"E049$Điều gì khiến bạn cảm thấy 'tội lỗi' nhất khi làm điều gì?",
"E050$Điều gì khiến bạn cảm thấy tự tin và hạnh phúc nhất về bản thân?",
"E051$Bạn có bao giờ lén lút đọc tin nhắn của người khác chưa?",
"E052$Ai là người bạn tin tưởng nhất trên đời?",
"E053$Bạn có bao giờ 'ăn trộm' đồ ăn của người khác chưa?",
"E054$Nếu bạn có thể thay đổi cách mọi người nhìn nhận bạn, bạn sẽ thay đổi điều gì?",
"E055$Bạn sẽ làm gì nếu bạn đột nhiên trở thành người duy nhất trên Trái Đất?",
"E056$Bạn có bao giờ cảm thấy mình là một gánh nặng cho gia đình không?",
"E057$Điều gì khiến bạn cảm thấy mình không xứng đáng với tình yêu/hạnh phúc?",
"E058$Bạn có tin rằng con người về bản chất là tốt hay xấu không?",
"E059$Bạn có bao giờ giả vờ ốm để được nghỉ học/nghỉ làm chưa?",
"E060$Bạn đã bao giờ giả vờ ốm để được nghỉ học chưa?",
"E061$Bạn thích tắm vòi sen hay tắm bồn hơn?",
"E062$Bạn thích nhận quà bất ngờ hay được hỏi trước khi mua hơn?",
"E063$Bí mật nào bạn chưa từng kể với ai trong nhóm?",
"E064$Bạn có bao giờ ghen tị với ai đó chưa?",
"E065$Bạn có một bí mật nào đó mà bạn chưa từng kể cho ai không?",
"E066$Bạn có một 'bí mật' nào đó về gia đình bạn mà bạn chưa từng kể cho ai không?",
"E067$Lần bạn 'quê độ' nhất trước mặt người lạ là khi nào?",
"E068$Bạn đã bao giờ phải lòng một nhân vật hư cấu chưa?",
"E069$Bạn sẽ làm gì nếu phát hiện bạn thân đang nói xấu mình?",
"E070$Bạn có một 'nguyên tắc' sống nào không bao giờ phá vỡ không?",
"E071$Bạn đã bao giờ nói dối rằng mình đã xem một bộ phim hoặc một cuốn sách nào đó để 'hợp' với mọi người chưa?",
"E072$Bạn đã từng làm điều gì 'ngu ngốc' nhất để gây ấn tượng với người khác?",
"E073$Kể về lần đầu tiên bạn gặp người bạn thân nhất của mình.",
"E074$Điều gì ở một người bạn khiến bạn khó chịu nhất nhưng bạn vẫn chấp nhận được?",
"E075$Bạn có nghĩ mình là một người tốt không?",
"E076$Lần cuối cùng bạn 'khóc' vì một người khác là khi nào?",
"E077$Nếu có một người theo dõi bạn cả ngày và ghi lại mọi việc bạn làm, họ sẽ thấy điều gì bất ngờ nhất?",
"E078$Nếu phải bị mắc kẹt ở một hòn đảo hoang với một người nào đó, bạn sẽ chọn ai trong nhóm chúng ta?",
"E079$Bạn có bao giờ 'tưởng tượng' mình là một người khác không?",
"E080$Nếu có thể trở lại quá khứ để thay đổi một điều về mối quan hệ của bạn với một người nào đó, bạn sẽ thay đổi điều gì?",
"E081$Nếu bạn biết một người thân của bạn đã phạm một tội ác nghiêm trọng, bạn có tố giác họ không?",
"E082$Điều gì bạn cảm thấy đáng sợ nhất ở người bạn thân nhất của mình?",
"E070$Bạn có một 'nguyên tắc' sống nào không bao giờ phá vỡ không?",
"E071$Bạn đã bao giờ nói dối rằng mình đã xem một bộ phim hoặc một cuốn sách nào đó để 'hợp' với mọi người chưa?",
"E072$Bạn đã từng làm điều gì 'ngu ngốc' nhất để gây ấn tượng với người khác?",
"E073$Kể về lần đầu tiên bạn gặp người bạn thân nhất của mình.",
"E074$Điều gì ở một người bạn khiến bạn khó chịu nhất nhưng bạn vẫn chấp nhận được?",
"E075$Bạn có nghĩ mình là một người tốt không?",
"E076$Lần cuối cùng bạn 'khóc' vì một người khác là khi nào?",
"E077$Nếu có một người theo dõi bạn cả ngày và ghi lại mọi việc bạn làm, họ sẽ thấy điều gì bất ngờ nhất?",
"E078$Nếu phải bị mắc kẹt ở một hòn đảo hoang với một người nào đó, bạn sẽ chọn ai trong nhóm chúng ta?",
"E079$Bạn có bao giờ 'tưởng tượng' mình là một người khác không?",
"E080$Nếu có thể trở lại quá khứ để thay đổi một điều về mối quan hệ của bạn với một người nào đó, bạn sẽ thay đổi điều gì?",
"E081$Nếu bạn biết một người thân của bạn đã phạm một tội ác nghiêm trọng, bạn có tố giác họ không?",
"E082$Điều gì bạn cảm thấy đáng sợ nhất ở người bạn thân nhất của mình?",
"E083$Kể về một kỷ niệm xấu hổ nhất của bạn và người bạn thân.",
"E073$Kể về lần đầu tiên bạn gặp người bạn thân nhất của mình.",
"E074$Điều gì ở một người bạn khiến bạn khó chịu nhất nhưng bạn vẫn chấp nhận được?",
"E075$Bạn có nghĩ mình là một người tốt không?",
"E076$Lần cuối cùng bạn 'khóc' vì một người khác là khi nào?",
"E077$Nếu có một người theo dõi bạn cả ngày và ghi lại mọi việc bạn làm, họ sẽ thấy điều gì bất ngờ nhất?",
"E078$Nếu phải bị mắc kẹt ở một hòn đảo hoang với một người nào đó, bạn sẽ chọn ai trong nhóm chúng ta?",
"E079$Bạn có bao giờ 'tưởng tượng' mình là một người khác không?",
"E080$Nếu có thể trở lại quá khứ để thay đổi một điều về mối quan hệ của bạn với một người nào đó, bạn sẽ thay đổi điều gì?",
"E081$Nếu bạn biết một người thân của bạn đã phạm một tội ác nghiêm trọng, bạn có tố giác họ không?",
"E082$Điều gì bạn cảm thấy đáng sợ nhất ở người bạn thân nhất của mình?",
"E078$Nếu phải bị mắc kẹt ở một hòn đảo hoang với một người nào đó, bạn sẽ chọn ai trong nhóm chúng ta?",
"E079$Bạn có bao giờ 'tưởng tượng' mình là một người khác không?",
"E080$Nếu có thể trở lại quá khứ để thay đổi một điều về mối quan hệ của bạn với một người nào đó, bạn sẽ thay đổi điều gì?",
"E081$Nếu bạn biết một người thân của bạn đã phạm một tội ác nghiêm trọng, bạn có tố giác họ không?",
"E082$Điều gì bạn cảm thấy đáng sợ nhất ở người bạn thân nhất của mình?",
"E083$Nếu có thể trở lại quá khứ để thay đổi một điều về mối quan hệ của bạn với một người nào đó, bạn sẽ thay đổi điều gì?",
"E081$Nếu bạn biết một người thân của bạn đã phạm một tội ác nghiêm trọng, bạn có tố giác họ không?",
"E082$Điều gì bạn cảm thấy đáng sợ nhất ở người bạn thân nhất của mình?",
"E083$Nếu bạn biết một người thân của bạn đã phạm một tội ác nghiêm trọng, bạn có tố giác họ không?",
"E084$Điều gì bạn cảm thấy đáng sợ nhất ở người bạn thân nhất của mình?",
"E085$Kể về một kỷ niệm xấu hổ nhất của bạn và người bạn thân.",
"E086$Bạn có từng 'phản bội' một người bạn thân chưa?",
"E087$Bạn có sẵn sàng tha thứ cho một người bạn đã phản bội mình không?",
"E088$Điều gì bạn cảm thấy đáng sợ nhất ở người bạn thân nhất của mình?",
"E089$Kể về một kỷ niệm xấu hổ nhất của bạn và người bạn thân.",
"E090$Bạn có từng 'phản bội' một người bạn thân chưa?",
"E091$Bạn có sẵn sàng tha thứ cho một người bạn đã phản bội mình không?",
"E091$Kể về một kỷ niệm xấu hổ nhất của bạn và người bạn thân.",
"E092$Bạn có từng 'phản bội' một người bạn thân chưa?",
"E093$Bạn có sẵn sàng tha thứ cho một người bạn đã phản bội mình không?",
"E094$Bạn có từng 'phản bội' một người bạn thân chưa?",
"E095$Bạn có sẵn sàng tha thứ cho một người bạn đã phản bội mình không?",
"E096$Bạn đã bao giờ nói 'tôi yêu bạn' với một người bạn thân chưa?",
"E097$Bạn đã từng 'crush' người yêu của bạn thân chưa?",
"E098$Bạn đã bao giờ 'thích' một người vì tính cách 'ngược ngạo' của họ chưa?",
"E099$Có điều gì bạn không thích ở một người bạn thân nhưng chưa bao giờ nói ra không?",
"E100$Bạn đã bao giờ phải lòng một người bạn thân chưa?",
`___None____.School.E$Bạn có "đảo ngược" lại lời hứa sẽ giúp một bạn học chỉ vì người đó không làm theo ý bạn không?`,
`_Kiêu_Ngạo_.School.E$Điều gì là lời nhận xét kiêu ngạo nhất bạn từng nói về điểm kém của một người bạn?`,
`___None____.School.E$Bạn đã "kết hợp" hai bài viết của người khác như thế nào để tạo ra một bài luận của riêng mình?`,
`_Tham_Lam__.School.E$Bạn đã bao giờ lấy trộm bút hoặc dụng cụ học tập đắt tiền của người khác chưa?`,
`___None____.School.E$Ai là người bạn đã "thay thế" vai trò thủ lĩnh nhóm bằng cách lén lút chỉ đạo các thành viên khác sau lưng họ?`,
`_Lười_Biếng.School.E$Bạn đã "tận dụng" những giờ tự học ở thư viện để làm việc riêng/ngủ như thế nào?`,
`___None____.School.E$Tại sao bạn lại "sửa đổi" nội dung một cuốn sách của thư viện trước khi trả lại?`,
`___Đố_Kị___.School.E$Khi nào là lần gần nhất bạn giả vờ chúc mừng thành công của một người bạn trong khi lòng bạn đang ghen tị?`,
`_Phẫn_Nộ___.School.E$Điều gì là lời nói cay độc nhất bạn từng tung ra để khiến một người bạn khóc trong giờ ra chơi?`,
`___None____.School.E$Bạn có "thích nghi" bằng cách liên tục tỏ ra ốm yếu để tránh các bài kiểm tra nói trước đám đông không?`,
`__Dâm_Dục__.School.E$Ai là người bạn đã cố gắng "hối lộ" bằng một món quà đắt tiền để họ làm bài tập hộ bạn?`,
`___None____.School.E$Bạn đã "sửa đổi" kết quả khảo sát ẩn danh của trường như thế nào để làm lợi cho bạn hoặc nhóm của bạn?`,
`_Tham_Lam__.School.E$Tại sao bạn lại tiếp tục vay tiền của bạn bè mà không có ý định trả lại, mặc dù bạn có khả năng?`,
`___None____.School.E$Bạn đã "loại bỏ" chi tiết nào trong lời nói của giáo viên để làm cho đồng đội của bạn hiểu sai và thất bại?`,
`_Kiêu_Ngạo_.School.E$Ở đâu bạn đã "tận dụng" quyền lực của mình (ví dụ: lớp trưởng) để bắt nạt người yếu hơn?`,
`___None____.School.E$Bạn có "kết hợp" lời đe dọa nhẹ nhàng với sự giúp đỡ để ép buộc người khác làm bài tập nhóm cho mình không?`,
`___Đố_Kị___.School.E$Điều gì là tin đồn sai sự thật bạn đã cố tình lan truyền về một bạn học để họ không thể ứng cử vào vị trí cao?`,
`___None____.Social.E$Bạn có "đảo ngược" thói quen sinh hoạt của mình để luôn sẵn sàng đăng ảnh vào "giờ vàng" (prime time) không?`,
`_Kiêu_Ngạo_.Social.E$Khi nào là lần cuối bạn công khai chỉ trích cách người khác sử dụng mạng xã hội (dù họ không hỏi)?`,
`___None____.Social.E$Bạn đã "kết hợp" các hashtag vô nghĩa như thế nào để bài đăng của bạn có vẻ hợp thời trang?`,
`_Tham_Lam__.Social.E$Ai là người bạn đã giả vờ thân thiết để được tag vào bài đăng và câu tương tác?`,
`___None____.Social.E$Tại sao bạn lại "thay thế" cảm xúc thật bằng những biểu tượng cảm xúc (emoji) tích cực thái quá trong mọi bình luận?`,
`_Lười_Biếng.Social.E$Bạn đã "tận dụng" tính năng tự động trả lời tin nhắn như thế nào để trốn tránh việc trò chuyện thật sự?`,
`___None____.Social.E$Điều gì là chi tiết cá nhân quan trọng nhất bạn đã cố tình "sửa đổi" trên hồ sơ để tránh bị người quen phát hiện?`,
`___Đố_Kị___.Social.E$Khi nào bạn đã bỏ theo dõi một group chat chỉ vì một người bạn có vẻ thân thiết hơn với những người khác trong đó?`,
`_Phẫn_Nộ___.Social.E$Bạn đã bày tỏ sự tức giận với một thương hiệu trên mạng như thế nào để được đền bù nhiều hơn mức xứng đáng?`,
`___None____.Social.E$Bạn có "thích nghi" bằng cách tạo ra một nhân vật hoàn toàn khác biệt trên mạng so với con người thật của mình để thu hút người theo dõi không?`,
`__Dâm_Dục__.Social.E$Điều gì là nội dung bạn đã cố ý đăng tải để khơi gợi sự chú ý cá nhân (ví dụ: tin nhắn riêng, cuộc gọi video) từ người bạn thích?`,
`___None____.Social.E$Ai là người bạn đã nhờ vả để "sửa đổi" hình thể của bạn trong ảnh bằng công cụ chỉnh sửa chuyên nghiệp?`,
`_Tham_Lam__.Social.E$Tại sao bạn lại mua lượt theo dõi/lượt thích giả để làm tăng giá trị khi săn các hợp đồng quảng cáo nhỏ?`,
`___None____.Social.E$Bạn đã "loại bỏ" tất cả các bằng chứng nào (bình luận, tin nhắn) có thể làm giảm đi sự nổi tiếng giả tạo của bạn?`,
`_Kiêu_Ngạo_.Social.E$Ở đâu bạn đã "tận dụng" danh tiếng trên mạng xã hội để nhận đồ miễn phí (ăn uống, dịch vụ) dù bạn không thực sự muốn quảng bá?`,
`___None____.Social.E$Bạn có "kết hợp" các bình luận của nhiều người khác thành một bình luận duy nhất của bạn để thể hiện sự thông thái không?`,
`___Đố_Kị___.Social.E$Điều gì là câu chuyện "drama" bạn đã cố tình lan truyền về một influencer đối thủ để hạ bệ họ?`,
`___None____.Funk.E$Bạn có "đảo ngược" lại câu chuyện về nỗi sợ của mình, biến nó thành một câu chuyện về lòng can đảm giả tạo không?`,
`_Kiêu_Ngạo_.Funk.E$Điều gì là lời nhận xét kiêu ngạo nhất bạn từng nói để che đậy nỗi sợ bị từ chối?`,
`___None____.Funk.E$Bạn đã "kết hợp" sự im lặng của mình với sự đồng tình giả tạo như thế nào vì sợ phải tranh luận?`,
`_Tham_Lam__.Funk.E$Ai là người bạn đã cố tình nói dối về khả năng tài chính của mình vì sợ bị họ lợi dụng?`,
`___None____.Funk.E$Tại sao bạn lại "thay thế" việc đối diện với nỗi sợ bằng cách liên tục chuyển sang một chủ đề khác trong các cuộc trò chuyện?`,
`_Lười_Biếng.Funk.E$Bạn đã "tận dụng" những triệu chứng căng thẳng giả như thế nào để tránh phải làm một công việc mà bạn sợ hãi?`,
`___None____.Funk.E$Điều gì là thông tin về quá khứ của bạn bạn đã cố tình "sửa đổi" vì sợ bị đánh giá?`,
`___Đố_Kị___.Funk.E$Khi nào là lần gần nhất bạn bí mật cầu nguyện điều tồi tệ xảy đến với một người mà bạn sợ hãi?`,
`_Phẫn_Nộ___.Funk.E$Bạn đã phản ứng bằng sự giận dữ như thế nào để che đậy nỗi sợ bị chỉ trích trong một cuộc họp quan trọng?`,
`___None____.Funk.E$Bạn có "thích nghi" bằng cách phát triển một câu chuyện giả về một căn bệnh tâm lý vì sợ phải làm việc quá sức không?`,
`__Dâm_Dục__.Funk.E$Điều gì là thông tin riêng tư bạn đã nói dối để người khác không thể sử dụng nó để đe dọa bạn?`,
`___None____.Funk.E$Ai là người bạn đã nhờ vả để "sửa đổi" bằng chứng về việc bạn đã sợ hãi không dám làm một việc gì đó?`,
`_Tham_Lam__.Funk.E$Tại sao bạn lại cố tình làm mất uy tín của một đối thủ cạnh tranh vì sợ bị họ đánh bại?`,
`___None____.Funk.E$Bạn đã "loại bỏ" những tin nhắn/email nào có thể tiết lộ nỗi sợ của bạn về một quyết định lớn?`,
`_Kiêu_Ngạo_.Funk.E$Ở đâu bạn đã "tận dụng" vị trí quyền lực của mình để đe dọa người khác phải sợ hãi và phục tùng bạn?`,
`___None____.Funk.E$Bạn có "kết hợp" hai nỗi sợ khác nhau của mình để tạo ra một lời bào chữa hoàn hảo cho việc không làm được việc không?`,
`___Đố_Kị___.Funk.E$Điều gì là lời dối trá bạn đã cố tình lan truyền về một người bạn vì sợ họ được mọi người yêu quý hơn bạn?`,

"D001$Bạn có bao giờ bịa chuyện về một ai đó để được nổi tiếng chưa?",
"D002$Bạn đã từng bị say xỉn và làm một việc gì đó điên rồ chưa?",
"D003$Bạn nghĩ gì về việc 'ngoại tình'?",
"D004$Bạn đã từng gửi nhầm tin nhắn 'nhạy cảm' chưa?",
"D005$Bạn có bao giờ 'nói xấu' bạn bè của mình chưa?",
"D006$Lần bạn 'phạm' một điều luật 'quan trọng' là khi nào?",
"D007$Nếu được 'đổi' một điều về cuộc đời mình, bạn sẽ đổi điều gì?",
"D008$Bạn đã từng 'bị' lừa đảo qua mạng xã hội chưa?",
"D009$Nếu bạn chỉ còn một ngày để sống, bạn sẽ làm gì?",
"D010$Điều gì khiến bạn sợ hãi nhất?",
"D011$Kể về lần gần nhất bạn ăn trộm hoặc lấy cắp một thứ gì đó.",
"D012$Nếu có một siêu năng lực, bạn muốn có siêu năng lực gì?",
"D013$Kể về một lần bạn bị mất mặt ở nơi công cộng.",
"D014$Nếu phải sống trên một hoang đảo, bạn muốn mang theo 3 thứ gì?",
"D015$Điều gì là ước mơ điên rồ nhất bạn chưa bao giờ dám nói ra?",
"D016$Kể về một lần bạn bị áp lực phải làm điều gì đó trái với đạo đức bản thân.",
"D017$Nếu thần đèn ban cho bạn ba điều ước, bạn sẽ cầu xin điều gì và tại sao?", 
"D018$Bạn đã bao giờ phớt lờ ai đó chưa?",
"D019$Nỗi đau thể xác tồi tệ nhất mà bạn từng trải qua là gì?",
"D020$Nếu có thể thay đổi một điều về bản thân bạn chỉ trong 24 giờ, bạn sẽ thay đổi điều gì và tại sao?",
"D021$Bạn đã bao giờ 'đánh cắp' một món đồ nhỏ nào đó chỉ vì muốn sở hữu nó chưa?",
"D022$Bạn đã từng 'phản bội' lòng tin của ai đó chưa?",
"D023$Bạn có từng viết một lá thư tình hoặc một bài thơ cho ai đó chưa?",
"D024$Bạn có từng 'lục lọi' điện thoại của ai đó chưa?",
"D025$Nếu một ngày bạn thức dậy và có thể nói chuyện với động vật, con vật đầu tiên bạn muốn trò chuyện là gì?",
"D026$Bạn đã bao giờ 'lén lút' đi chơi ở một nơi mà bố mẹ bạn cấm chưa?",
"D027$Bạn có một nỗi sợ hãi nào 'kỳ cục' không?",
"D028$Bạn có thể kể về lần đầu tiên 'tò mò' về giới tính không?",
"D029$Bạn có một thói quen 'kỳ lạ' nào liên quan đến giấc ngủ không?",
"D030$Bạn nghĩ gì về 'tình yêu' qua 'tình một đêm'?",
"D031$Bạn tin vào ma quỷ hay thế giới tâm linh không?",
"D032$Bạn có tin tưởng ai trong nhóm này tuyệt đối không? Nếu không, tại sao?",
"D033$Bạn có từng nghĩ đến việc 'bỏ trốn' khỏi nhà không?",
"D034$Bạn có bao giờ tự hỏi liệu cuộc sống của bạn có thật sự 'tốt' như bạn vẫn thể hiện ra không?",
"D035$Bạn có một nỗi sợ hãi 'vô lý' nào không?",
"D036$Nếu tiền không phải là vấn đề, bạn sẽ làm gì mỗi ngày?",
"D037$Bạn có một 'tật xấu' nào mà bạn bè không biết không?",
"D038$Bạn có tin vào ma quỷ hay những điều siêu nhiên không?",
"D039$Bạn nghĩ 'tình yêu sét đánh' có thật không?",
"D040$Bạn có từng 'ăn cắp' bản quyền của ai đó chưa?",
"D041$Bạn đã bao giờ khóc vì một cuốn sách/bộ phim chưa?",
"D042$Lần cuối cùng bạn khóc là vì chuyện gì?",
"D043$Nếu có thể biến một thứ bất kỳ thành món tráng miệng, bạn sẽ chọn cái gì?",
"D044$Nếu bạn có thể 'tẩy não' một kỷ niệm trong quá khứ, bạn sẽ xóa đi kỷ niệm nào?",
"D045$Điều gì khiến bạn cảm thấy hối tiếc nhất trong cuộc đời?",
"D046$Điều gì khiến bạn cảm thấy 'tội lỗi' nhất khi làm điều gì?",
"D047$Điều gì khiến bạn cảm thấy tự tin và hạnh phúc nhất về bản thân?",
"D048$Điều gì khiến bạn cảm thấy an toàn và thoải mái khi ở bên cạnh ai đó?",
"D049$Bạn đã từng 'thả thính' cùng lúc nhiều người chưa?",
"D050$Bạn có từng giả vờ mình là người khác trên mạng xã hội chưa?",
"D051$Bạn có bao giờ 'lén lút' nghe lén cuộc trò chuyện của người khác chưa?",
"D052$Nếu bạn đột nhiên trở thành người duy nhất trên Trái Đất, bạn sẽ làm gì?",
"D053$Điều gì ở người khác mà bạn ngưỡng mộ nhất?",
"D054$Bạn đã bao giờ lừa dối người yêu chưa?",
"D055$Bạn có một 'cách' để 'được lòng' người khác không?",
"D056$Bạn có từng 'phá hoại' một mối quan hệ của người khác không?",
"D057$Bạn có từng 'sáng tác' ra một câu chuyện hoặc một lời nói dối chỉ để thoát khỏi rắc rối chưa?",
"D058$Người chơi nào sẽ sống sót sau thảm họa zombie và ai sẽ là người đầu tiên ra đi?",
"D059$Nếu bạn chỉ được xem phim hài lãng mạn hoặc phim kinh dị trong suốt quãng đời còn lại, bạn sẽ chọn phim nào và tại sao?",
"D060$Bí mật nào bạn chưa từng kể với ai trong nhóm?",
"D061$Bạn có một sở thích nào 'kỳ lạ' không?",
"D062$Nếu được chọn, bạn muốn làm người yêu của ai trong nhóm này?",
"D063$Bạn có từng 'bắt nạt' một ai đó mà bạn không thích chưa?",
"D064$Lần bạn làm 'quê' người khác trước mặt đám đông là khi nào?",
"D065$Bạn đã bao giờ phải lòng một nhân vật hư cấu chưa?",
"D066$Điều gì khiến bạn cảm thấy bị cô lập hoặc lạc lõng trong một nhóm đông người?",
"D067$Bạn có tin vào lời nguyền không?",
"D068$Bạn có một 'nguyên tắc' nào về tình yêu không bao giờ phá vỡ không?",
"D069$Bạn đã bao giờ nói dối rằng mình đã xem một bộ phim hoặc một cuốn sách nào đó để 'hợp' với mọi người chưa?",
"D070$Lần đầu tiên bạn bị 'thất tình' là khi nào?",
"D071$Bạn có một bí mật 'lớn' nào về người yêu cũ của bạn không?",
"D072$Bạn có ghen tị với thành công của người khác không?",
"D073$Bạn có một sở thích 'đặc biệt' nào mà bạn không muốn ai biết không?",
"D074$Bạn đã từng 'dụ dỗ' một người nào đó để đạt được mục đích của mình chưa?",
"D075$Điều gì ở một người bạn khiến bạn khó chịu nhất nhưng bạn vẫn chấp nhận được?",
"D076$Điều gì bạn nghĩ là tệ' nhất khi bạn có một người bạn trai/bạn gái?",
"D077$Món quà ý nghĩa nhất bạn từng nhận được từ một người bạn là gì?",
"D078$Nếu có thể cho một người bạn bất kỳ một lời khuyên, bạn sẽ nói gì?",
"D079$Bạn có thể mô tả một người bạn 'hoàn hảo' là như thế nào không?",
"D080$Bạn có bao giờ 'nói xấu' một người nào đó ngay trước mặt họ chưa?",
"D081$Nếu phải bị mắc kẹt ở một hòn đảo hoang với một người nào đó, bạn sẽ chọn ai trong nhóm chúng ta?",
"D082$Bạn có bao giờ 'tưởng tượng' mình là một người 'tồi tệ' không?",
"D083$Bạn có từng nói dối bạn bè để được đi chơi với người bạn thích chưa?",
"D084$Nếu có thể trở lại quá khứ để thay đổi một điều về mối quan hệ của bạn với một người nào đó, bạn sẽ thay đổi điều gì?",
"D085$Bạn đã bao giờ cảm thấy 'thất vọng' về một người bạn chưa?",
"D086$Nếu bạn biết được một bí mật đen tối của một người bạn, bạn sẽ nói ra hay giữ im lặng?",
"D087$Bạn có thích một người đã có người yêu chưa?",
"D088$Lần cuối cùng bạn 'ghen' với một người khác là khi nào?",
"D089$Bạn đã bao giờ phải lòng một người đã có người yêu chưa?",
"D090$Bạn có bao giờ 'thích' một người mà bạn biết họ có 'vấn đề' chưa?",
"D091$Bạn có bao giờ nói xấu sau lưng một người bạn thân chưa?",
"D092$Bạn đã từng 'để ý' đến một người bạn thân chưa?",
"D093$Bạn đã bao giờ nói tôi yêu bạn' với một người bạn thân chưa?",
"D094$Bạn có thể kể một kỷ niệm đáng nhớ với một người bạn thân mà bạn không muốn ai biết không?",
"D095$Bạn đã từng 'chia sẻ' bí mật của một người bạn với người khác chưa?",
"D096$Bạn đã bao giờ cảm thấy ghen tị với một người bạn chưa?",
"D097$Bạn có một 'bí mật' nào với một người bạn thân mà bạn không muốn ai biết không?",
"D098$Bạn đã bao giờ 'thích' một người vì 'gu' thời trang của họ chưa?",
"D099$Điều gì bạn nghĩ là 'tệ' nhất khi bạn có một người bạn thân khác giới?",
"D100$Bạn đã từng làm điều gì táo bạo nhất để 'hạ gục' một người bạn đã 'crush'?",
`___None____.School.D$Khi nào bạn đã "thay thế" chữ ký của phụ huynh để trốn tránh một cuộc họp quan trọng với giáo viên?`,
`_Lười_Biếng.School.D$Bạn đã "đảo ngược" tình huống như thế nào để biến việc bạn quên làm bài thành lỗi của người nhắc nhở bạn?`,
`___None____.School.D$Tại sao bạn lại "thích nghi" với sự cô lập của một người bạn bằng cách tham gia vào việc xa lánh họ?`,
`_Phẫn_Nộ___.School.D$Bạn có từng cố tình nói dối để một người bạn bị thầy cô giáo phạt oan không?`,
`___None____.School.D$Ai là người bạn đã "sửa đổi" điểm số của họ trong một danh sách công khai để bạn trông nổi bật hơn?`,
`__Dâm_Dục__.School.D$Điều gì bạn đã sử dụng để làm "mồi nhử" một bạn học có ảnh hưởng để họ trở thành "tay sai" của bạn?`,
`___None____.School.D$"Ở đâu" bạn đã "kết hợp" việc trốn học với bạn bè để thực hiện một hành vi mà bạn biết là nguy hiểm?`,
`_Tham_Lam__.School.D$Bạn đã làm gì để "loại bỏ" một đối thủ cạnh tranh khỏi cuộc thi học thuật quan trọng (ví dụ: giấu tài liệu)?`,
`___None____.School.D$Tại sao bạn "thay thế" sự thật về việc bạn vi phạm nội quy bằng cách đổ lỗi cho một học sinh mới?`,
`_Kiêu_Ngạo_.School.D$Bạn có từng cố ý làm bẽ mặt một bạn học trước lớp chỉ để chứng tỏ sự vượt trội của mình không?`,
`___None____.School.D$Bạn đã "tận dụng" những lời nói chia sẻ bí mật của bạn mình như thế nào để gây áp lực cho họ?`,
`___Đố_Kị___.School.D$Khi nào bạn đã "thổi phồng" một lỗi sai nhỏ của người khác để họ bị giáo viên khiển trách nặng?`,
`___None____.School.D$Ai là người mà bạn đã "đảo ngược" mọi cáo buộc nhắm vào bạn và chuyển hướng sang người đó?`,
`_Lười_Biếng.School.D$Điều gì là bài kiểm tra bạn đã gian lận tinh vi nhất mà không bị phát hiện?`,
`___None____.School.D$Bạn đã "sửa đổi" thông tin cá nhân của một bạn học bằng cách nào để biến họ thành trò cười trên mạng xã hội?`,
`_Phàm_Ăn___.School.D$Bạn có từng ăn trộm tiền trong quỹ lớp để mua đồ ăn không?`,
`_Phẫn_Nộ___.School.D$Điều gì là tài sản của trường mà bạn đã cố tình "loại bỏ" (phá hủy) vì tức giận với quyết định của ban giám hiệu?`,
`___None____.Social.D$Khi nào bạn đã "thay thế" hình ảnh đời thực bằng những bức ảnh deep-fake hoặc ảnh AI để lừa bạn bè?`,
`_Lười_Biếng.Social.D$Bạn đã "đảo ngược" lại nội dung bị chỉ trích của mình như thế nào để biến nó thành một câu chuyện thành công giả tạo?`,
`___None____.Social.D$Tại sao bạn lại "thích nghi" bằng cách chỉ kết bạn với những người có độ tương tác cao để tăng reach cá nhân?`,
`_Phẫn_Nộ___.Social.D$Bạn có từng cố tình gửi nhiều báo cáo (report) giả về một người để tài khoản của họ bị khóa không?`,
`___None____.Social.D$Ai là người bạn đã "sửa đổi" câu chuyện của họ thành câu chuyện của bạn và đăng lên để được khen ngợi?`,
`__Dâm_Dục__.Social.D$Điều gì là bí mật cá nhân của người khác mà bạn đã dùng làm "cần câu" để giữ họ lại gần mình trên mạng?`,
`___None____.Social.D$"Ở đâu" bạn đã "kết hợp" hai địa điểm khác nhau trong một bức ảnh để giả mạo một chuyến đi xa hoa?`,
`_Tham_Lam__.Social.D$Bạn đã "loại bỏ" bằng chứng về việc mình nhận được sản phẩm miễn phí (quảng cáo) nhưng không hề sử dụng nó như thế nào?`,
`___None____.Social.D$Tại sao bạn lại "thay thế" việc trò chuyện công khai bằng tin nhắn riêng với tất cả mọi người để tạo ấn tượng về sự bí ẩn và độc quyền?`,
`_Kiêu_Ngạo_.Social.D$Bạn có từng công khai làm bẽ mặt một người bình luận (commenter) trên bài đăng của bạn chỉ để thể hiện quyền lực không?`,
`___None____.Social.D$Bạn đã "tận dụng" tin nhắn riêng tư của bạn mình như thế nào để làm trò cười cho nhóm bạn khác?`,
`___Đố_Kị___.Social.D$Khi nào bạn đã tạo tài khoản giả để bình luận tiêu cực ẩn danh về thành công của một người bạn?`,
`___None____.Social.D$Ai là người mà bạn đã "đảo ngược" lời nói của họ để biến họ thành kẻ nói dối trước công chúng trên mạng?`,
`_Lười_Biếng.Social.D$Điều gì là phần mềm hoặc dịch vụ bạn sử dụng để tự động đăng bài và trả lời bình luận để khỏi phải tương tác thật?`,
`___None____.Social.D$Bạn đã "sửa đổi" thông tin liên quan đến sức khỏe/tâm lý của mình như thế nào để nhận được sự thương cảm và tương tác?`,
`_Phàm_Ăn___.Social.D$Bạn có từng giả vờ là người nghèo khó trên các nhóm từ thiện để nhận phiếu giảm giá hoặc đồ ăn không?`,
`_Phẫn_Nộ___.Social.D$Điều gì là thông tin cá nhân của một người mà bạn đã cố tình "loại bỏ" (xóa bỏ) khỏi hồ sơ của họ để gây hại?`,
`___None____.Funk.D$Khi nào bạn đã "thay thế" sự thật về nỗi sợ hãi bị bỏ rơi bằng cách kiểm soát mọi hoạt động của người yêu?`,
`_Lười_Biếng.Funk.D$Bạn đã "đảo ngược" trách nhiệm của mình như thế nào để đổ lỗi cho người khác vì sự Lười biếng xuất phát từ sợ hãi của bạn?`,
`___None____.Funk.D$Tại sao bạn lại "thích nghi" bằng cách trở thành một người luôn đồng ý với mọi người vì sợ bị từ chối?`,
`_Phẫn_Nộ___.Funk.D$Bạn có từng cố tình nói dối để một người bạn bị phạt oan chỉ vì họ làm bạn sợ hãi?`,
`___None____.Funk.D$Ai là người bạn đã "sửa đổi" cảm xúc của họ bằng cách nói rằng bạn sợ họ sẽ rời bỏ bạn nếu bạn không làm theo ý họ?`,
`__Dâm_Dục__.Funk.D$Điều gì là lời hứa bạn đã đưa ra để người khác chấp nhận một yêu cầu mà họ sợ hãi (ví dụ: tham gia vào một hoạt động nguy hiểm)?`,
`___None____.Funk.D$"Ở đâu" bạn đã "kết hợp" việc trốn khỏi một tình huống sợ hãi với hành vi vi phạm pháp luật nhỏ?`,
`_Tham_Lam__.Funk.D$Bạn đã "loại bỏ" bằng chứng về việc bạn nhận tiền bất chính như thế nào vì sợ bị phát hiện?`,
`___None____.Funk.D$Tại sao bạn "thay thế" sự thật về việc bạn bị lừa dối bằng một câu chuyện về lòng can đảm của mình?`,
`_Kiêu_Ngạo_.Funk.D$Bạn có từng cố ý làm bẽ mặt một người khác trước đám đông chỉ để chứng tỏ bạn không sợ hãi?`,
`___None____.Funk.D$Bạn đã "tận dụng" hồ sơ bệnh án hoặc ghi chú tâm lý của mình như thế nào để tránh phải đối diện với nỗi sợ hãi?`,
`___Đố_Kị___.Funk.D$Khi nào bạn đã cố tình làm chậm tiến độ của một người đồng nghiệp vì sợ họ được thăng chức trước bạn?`,
`___None____.Funk.D$Ai là người mà bạn đã "đảo ngược" mọi cáo buộc sợ hãi nhắm vào bạn và chuyển hướng sang người đó?`,
`_Lười_Biếng.Funk.D$Điều gì là lời dối trá bạn đã sử dụng để tránh phải đi khám bác sĩ vì sợ bị phát hiện bệnh?`,
`___None____.Funk.D$Bạn đã "sửa đổi" thông tin cá nhân của một người khác bằng cách nào để khiến họ sợ bị bóc mẽ trên mạng xã hội?`,
`_Phàm_Ăn___.Funk.D$Bạn có từng ăn cắp thức ăn của người khác vì sợ họ sẽ không chia sẻ cho bạn không?`,
`_Phẫn_Nộ___.Funk.D$Điều gì là tài liệu quan trọng của người khác mà bạn đã cố tình "loại bỏ" (xé, đốt) vì sợ nó sẽ gây hại cho bạn?`,

"C001$Bạn đã từng làm 'chuyện ấy' với ai chưa?",
"C002$Bạn có bao giờ dùng 'sextoys' chưa?",
"C003$Bạn có bao giờ 'thủ dâm' ở nơi công cộng chưa?",
"C004$Bạn đã từng quay 'clip' nhạy cảm chưa?",
"C005$Bạn có bao giờ xem 'phim đen' chưa?",
"C006$Lần bạn 'phạm' một điều luật 'quan trọng' là khi nào?",
"C007$Nếu được 'đổi' một điều về cuộc đời mình, bạn sẽ đổi điều gì?",
"C008$Bạn đã từng 'bị' lừa đảo qua mạng xã hội chưa?",
"C009$Bạn có bao giờ bị “bắt cá hai tay” hoặc 'cắm sừng' chưa?",
"C010$Nếu có thể xóa một kỷ niệm xấu ra khỏi bộ nhớ, bạn sẽ xóa điều gì?",
"C011$Nơi kỳ lạ nhất mà bạn từng đi vệ sinh là ở đâu?",
"C012$Bạn đã bao giờ 'bị từ chối' một cách 'đau lòng' chưa?",
"C013$Bạn nghĩ điều gì là quan trọng nhất trong một mối quan hệ?",
"C014$Bạn nghĩ 'chia tay' một cách tốt nhất là như thế nào?",
"C015$Bạn nghĩ gì về tình yêu 'một đêm'?",
"C016$Bạn có một 'ám ảnh' nào đó về tình dục không?",
"C017$Bạn có bao giờ bị 'đánh cắp' một nụ hôn chưa?",
"C018$Bạn có thể kể về lần đầu tiên 'quan hệ' của mình không?",
"C019$Bạn có nghĩ 'tình dục' là điều quan trọng trong tình yêu không?",
"C020$Bạn có một thói quen 'kỳ lạ' nào liên quan đến tình yêu không?",
"C021$Bạn nghĩ gì về 'tình yêu' qua 'tình một đêm'?",
"C022$Kể về lần đầu tiên bạn biết yêu.",
"C023$Bạn có từng tự làm tổn thương bản thân không? (Về cả thể chất và tinh thần)",
"C024$Bạn có tin vào “karma” (luật nhân quả) không?",
"C025$Bạn có sợ cái chết không? Vì sao?",
"C026$Bạn nghĩ 'tình yêu đích thực' là gì?",
"C027$Bạn đã bao giờ làm một điều gì 'điên rồ' chỉ vì tình yêu chưa?",
"C028$Lần cuối cùng bạn khóc là khi nào và vì sao?",
"C029$Bạn có từng bị 'bắt nạt' (bắt nạt học đường, bắt nạt công sở...) chưa? Kể về trải nghiệm đó.",
"C030$Nếu có thể đổi chỗ cho một cặp đôi nổi tiếng, bạn sẽ chọn ai?",
"C031$Nếu có thể quay lại quá khứ, bạn sẽ thay đổi điều gì trong một mối quan hệ đã kết thúc?",
"C032$Nếu phải chọn, bạn sẽ chọn tình yêu hay sự nghiệp?",
"C033$Điều gì bạn cảm thấy nuối tiếc nhất trong cuộc đời?",
"C034$Bạn có bao giờ 'lén lút' nghe lén cuộc trò chuyện của người khác chưa?",
"C035$Bạn đã từng có ý nghĩ 'ngoài luồng' với người yêu của bạn chưa?",
"C036$Bạn có một 'cách' để 'được lòng' người khác không?",
"C037$Bạn đã bao giờ lén kiểm tra điện thoại của người yêu chưa?",
"C038$Điều điên rồ nhất bạn từng làm cho người mình yêu là gì?",
"C039$Kể về lần bạn nói dối cha mẹ một chuyện lớn.",
"C040$Điều gì khiến bạn thấy xấu hổ nhất về bản thân?",
"C041$Bạn thích 'hẹn hò' truyền thống hay 'hẹn hò' hiện đại hơn?",
"C042$Bí mật đen tối nhất mà bạn chưa từng tiết lộ cho ai là gì?",
"C043$Điều gì khiến bạn ghen tuông nhất trong một mối quan hệ?",
"C044$Bạn có một bí mật 'đen tối' nào chưa từng kể cho ai không?",
"C045$Bạn có một bí mật tình cảm nào mà bạn chưa từng kể với ai không?",
"C046$Bạn đã bao giờ phải lòng một nhân vật hư cấu trong phim hoặc sách chưa?",
"C047$Bạn đã bao giờ có tình cảm với bạn thân của mình chưa?",
"C048$Bạn có tin vào lời nguyền không?",
"C049$Bạn có một 'nguyên tắc' nào về tình yêu không bao giờ phá vỡ không?",
"C050$Kể một lần bạn bị “friend-zone” hoặc “crush” từ chối.",
"C051$Mối tình 'crush' đầu tiên của bạn là với ai?",
"C052$Bạn thích người bạn đời lý tưởng của mình có 3 điểm gì?",
"C053$Bạn đã từng 'sáng tác' một bài hát hoặc một bài thơ cho người bạn thích chưa?",
"C054$Bạn có bao giờ 'tự sướng' chưa?",
"C055$Bạn đã bao giờ 'lén lút' đi chơi với người bạn thích mà không cho ai biết chưa?",
"C056$Bạn có một bí mật 'lớn' nào về người yêu cũ của bạn không?",
"C057$Bạn đã từng ngủ với một người lạ chưa?",
"C058$Điều gì ở một người khiến bạn 'rung động' ngay từ lần gặp đầu tiên?",
"C059$Bạn thích 'yêu thầm' hay 'yêu công khai' hơn?",
"C060$Lần bạn 'thất tình' mà bạn cảm thấy đau khổ nhất là khi nào?",
"C061$Bạn có bao giờ 'nói xấu' một người nào đó ngay trước mặt họ chưa?",
"C062$Bạn có bao giờ 'tưởng tượng' mình là một người 'tồi tệ' không?",
"C063$Bạn có bao giờ 'lên giường' với bạn thân của mình chưa?",
"C064$Lần cuối cùng bạn 'ghen' với một người khác là khi nào?",
"C065$Bạn có thể kể một kỷ niệm đáng nhớ với một người bạn thích mà bạn không muốn ai biết không?",
"C066$Bạn có bao giờ phải lòng một người đã có chủ chưa?",
"C067$Bạn đã từng 'phải lòng' một người đã có người yêu chưa?",
"C068$Bạn có bao giờ 'thích' một người mà bạn biết họ có 'vấn đề' chưa?",
"C069$Bạn đã bao giờ 'để ý' đến một người bạn thân chưa?",
"C070$Bạn đã bao giờ 'thích' một người vì 'gu' âm nhạc của họ chưa?",
`___None____.School.C$Bạn đã "tận dụng" quyền truy cập vào hệ thống điểm danh/điểm số của trường như thế nào để làm hại ai đó?`,
`__Dâm_Dục__.School.C$Tại sao bạn lại tiếp tục yêu cầu những hành động đáng xấu hổ từ một người mà bạn biết họ sẽ làm theo vì tình cảm với bạn?`,
`___None____.School.C$Ai là người bạn đã "kết hợp" với mình để tạo ra một chiến dịch bắt nạt trực tuyến nhắm vào một cá nhân?`,
`_Tham_Lam__.School.C$Bạn có cố ý làm mất giấy tờ quan trọng của một bạn học để bạn có cơ hội nhận được giải thưởng thay thế họ không?`,
`___None____.School.C$Ở đâu bạn đã "thay thế" thông báo chính thức của trường bằng một thông báo giả để lừa bạn bè của mình?`,
`_Kiêu_Ngạo_.School.C$Bạn đã "đảo ngược" câu chuyện về một vụ bạo lực học đường như thế nào để biến nạn nhân thành kẻ gây rối?`,
`___None____.School.C$Khi nào bạn đã "sửa đổi" một đoạn video nhạy cảm của bạn mình để lan truyền trên mạng xã hội?`,
`___Đố_Kị___.School.C$Điều gì là lời dối trá tàn nhẫn nhất bạn từng nói với một người để khiến họ từ bỏ ước mơ của mình?`,
`___None____.School.C$Bạn có "thích nghi" bằng cách giả vờ là người bạn của một người để lấy thông tin nhạy cảm của họ không?`,
`_Phẫn_Nộ___.School.C$Tại sao bạn quyết định làm hỏng bài kiểm tra (ví dụ: xé hoặc làm ướt) của một người bạn ngay trước khi nộp?`,
`___None____.School.C$Ai là người bạn đã cố gắng "loại bỏ" khỏi danh sách tham gia một chuyến đi quan trọng của trường bằng cách nói xấu họ?`,
`_Tham_Lam__.School.C$Bạn đã bao giờ nhận hối lộ từ một học sinh khác để che giấu hành vi gian lận của họ chưa?`,
`___None____.School.C$Điều gì là tài liệu mật của trường mà bạn đã "tận dụng" để trục lợi cá nhân hoặc nhóm?`,
`__Dâm_Dục__.School.C$Ở đâu bạn đã hẹn gặp riêng một người để gây áp lực buộc họ phải giữ bí mật không lành mạnh của bạn?`,
`___None____.School.C$Bạn đã "kết hợp" các tài khoản mạng xã hội giả như thế nào để tạo ra một cuộc tấn công quấy rối tinh thần có tổ chức?`,
`___Đố_Kị___.School.C$Bạn có "thay thế" sự thật về nguồn gốc bài tập lớn của mình bằng cách nói dối rằng bạn đã tự làm, trong khi là của người khác không?`,
`___None____.School.C$Tại sao bạn lại "đảo ngược" vai trò trong một cuộc tranh cãi, biến mình từ người bắt nạt thành nạn nhân để được an ủi?`,
`___None____.Social.C$Bạn đã "tận dụng" sự kiện tưởng niệm hoặc trend nhạy cảm như thế nào để câu tương tác cho bài đăng của bạn?`,
`__Dâm_Dục__.Social.C$Tại sao bạn lại tiếp tục trò chuyện với nhiều người cùng lúc với cùng một lời hứa hẹn cá nhân giả dối?`,
`___None____.Social.C$Ai là người bạn đã "kết hợp" với mình để tạo ra một câu chuyện lừa đảo phức tạp nhằm xin tiền trên mạng?`,
`_Tham_Lam__.Social.C$Bạn có cố ý làm mất uy tín của một đối thủ kinh doanh nhỏ trên mạng xã hội để thu lợi về cho bản thân không?`,
`___None____.Social.C$"Ở đâu" bạn đã "thay thế" nội dung quảng cáo thành một bài đăng từ thiện giả để lừa người khác chuyển tiền cho bạn?`,
`_Kiêu_Ngạo_.Social.C$Bạn đã "đảo ngược" sự thật về một vụ tranh cãi công khai như thế nào để biến mình thành nạn nhân và nhận sự đồng cảm?`,
`___None____.Social.C$Khi nào bạn đã "sửa đổi" tin nhắn riêng tư của một người khác thành lời đe dọa và công khai chúng?`,
`___Đố_Kị___.Social.C$Điều gì là lời dối trá hủy hoại danh tiếng bạn đã cố tình lan truyền về gia đình của một người bạn?`,
`___None____.Social.C$Bạn có "thích nghi" bằng cách giả vờ bị hack để đổ lỗi cho những tin nhắn tiêu cực/xúc phạm mà bạn đã gửi đi không?`,
`_Phẫn_Nộ___.Social.C$Tại sao bạn quyết định công khai số điện thoại/địa chỉ nhà của một người bạn chỉ vì họ không đồng ý với bạn?`,
`___None____.Social.C$Ai là người bạn đã cố gắng "loại bỏ" khỏi công việc/dự án bằng cách cung cấp thông tin sai sự thật về họ cho sếp/người quản lý?`,
`_Tham_Lam__.Social.C$Bạn đã bao giờ sử dụng danh tiếng trên mạng của mình để ép buộc người khác tặng quà/dịch vụ miễn phí chưa?`,
`___None____.Social.C$Điều gì là bí mật nhạy cảm của người khác mà bạn đã "tận dụng" để tống tiền họ đổi lấy sự im lặng?`,
`__Dâm_Dục__.Social.C$Ở đâu bạn đã tạo một trang cá nhân giả mạo để lừa người khác tiết lộ thông tin riêng tư nhạy cảm của họ?`,
`___None____.Social.C$Bạn đã "kết hợp" các bình luận giận dữ từ nhiều người như thế nào để tạo ra một chiến dịch tấn công report hàng loạt vào tài khoản đối thủ?`,
`___Đố_Kị___.Social.C$Bạn có "thay thế" thông tin tích cực về thành công của người khác bằng những lời lẽ tiêu cực nhằm giảm thiểu niềm vui của họ không?`,
`___None____.Social.C$Tại sao bạn lại "đảo ngược" lời nói của một người để họ trông có vẻ phân biệt đối xử hoặc sai trái đạo đức trong một cuộc tranh luận công khai?`,
`___None____.Funk.C$Bạn đã "tận dụng" sự sợ hãi của người khác về việc bị sa thải để buộc họ làm việc cho bạn mà không được trả công?`,
`__Dâm_Dục__.Funk.C$Tại sao bạn lại tiếp tục yêu cầu những hành động đáng xấu hổ từ một người mà bạn biết họ sợ bạn rời bỏ họ?`,
`___None____.Funk.C$Ai là người bạn đã "kết hợp" với mình để tạo ra một câu chuyện đe dọa nhằm khiến một người phải sợ hãi và bỏ cuộc?`,
`_Tham_Lam__.Funk.C$Bạn có cố ý làm mất giấy tờ của một người khác vì sợ họ sẽ giàu có hơn bạn?`,
`___None____.Funk.C$"Ở đâu" bạn đã "thay thế" thông báo chính thức bằng một thông báo giả để lừa người khác làm một việc mà họ sợ hãi?`,
`_Kiêu_Ngạo_.Funk.C$Bạn đã "đảo ngược" lại sự thật về một vụ bạo lực ngôn từ như thế nào để biến người bị tổn thương thành kẻ gây rối vì sợ bị lộ?`,
`___None____.Funk.C$Khi nào bạn đã "sửa đổi" tin nhắn riêng tư của một người đang sợ hãi để biến nó thành lời thú tội của họ?`,
`___Đố_Kị___.Funk.C$Điều gì là lời dối trá tàn nhẫn nhất bạn từng nói để khiến một người bạn sợ hãi không dám theo đuổi ước mơ của họ?`,
`___None____.Funk.C$Bạn có "thích nghi" bằng cách giả vờ là người bạn của một người chỉ để nắm được nỗi sợ lớn nhất của họ?`,
`_Phẫn_Nộ___.Funk.C$Tại sao bạn quyết định làm hỏng tài sản có giá trị tình cảm của người khác vì sợ rằng họ sẽ thành công hơn bạn?`,
`___None____.Funk.C$Ai là người bạn đã cố gắng "loại bỏ" khỏi công việc/dự án bằng cách cung cấp thông tin sai sự thật về nỗi sợ của họ?`,
`_Tham_Lam__.Funk.C$Bạn đã bao giờ nhận hối lộ từ một người khác để bạn giữ bí mật về nỗi sợ lớn nhất của họ chưa?`,
`___None____.Funk.C$Điều gì là bí mật nhạy cảm của người khác mà bạn đã "tận dụng" để đe dọa họ và khiến họ sợ hãi?`,
`__Dâm_Dục__.Funk.C$Ở đâu bạn đã hẹn gặp riêng một người để gây áp lực buộc họ phải giữ bí mật về hành vi lừa dối của bạn?`,
`___None____.Funk.C$Bạn đã "kết hợp" các tài khoản giả như thế nào để tạo ra một cuộc tấn công quấy rối tinh thần có tổ chức nhằm vào nỗi sợ của một người?`,
`___Đố_Kị___.Funk.C$Bạn có "thay thế" sự thật về một dự án bằng cách nói dối rằng nó thất bại vì sợ bị đồng nghiệp chỉ trích không?`,
`___None____.Funk.C$Tại sao bạn lại "đảo ngược" vai trò trong một vụ việc, biến mình từ kẻ đe dọa thành nạn nhân vì sợ bị trả thù?`,


"B001$Bạn đã từng 'tự tử' chưa?",
"B002$Bạn đã từng 'đánh cắp' một vật gì đó có giá trị lớn chưa?",
"B003$Bạn có bao giờ 'cực đoan' trong tình dục chưa?",
"B004$Bạn có thể kể về lần 'bị lạm dụng' chưa?",
"B005$Bạn có bao giờ 'bán dâm' chưa?",
"B006$Bạn có bao giờ 'cưỡng hiếp' ai đó chưa?",
"B007$Lần bạn 'phạm' một điều luật 'quan trọng' là khi nào?",
"B008$Nếu được 'đổi' một điều về cuộc đời mình, bạn sẽ đổi điều gì?",
"B009$Bạn đã từng 'bị' lừa đảo qua mạng xã hội chưa?",
"B010$Lần cuối cùng bạn đi vệ sinh ở một nơi “kỳ lạ” là khi nào?",
"B011$Kể về lần đầu tiên bạn thử hút thuốc (nếu có).",
"B012$Bạn đã bao giờ ăn trộm thứ gì chưa? Nếu có, đó là thứ gì?",
"B013$Nếu có thể thay đổi một điều về bản thân bạn chỉ trong 24 giờ, bạn sẽ thay đổi điều gì và tại sao?",
"B014$Bạn có từng 'phản bội' lòng tin của ai đó chưa?",
"B015$Bạn có một 'khao khát' tình dục kỳ lạ nào không?",
"B016$Bạn có một thói quen 'kỳ lạ' nào liên quan đến tình yêu không?",
"B017$Bạn nghĩ gì về 'tình yêu' qua 'tình một đêm'?",
"B018$Bạn có bao giờ tự hỏi liệu cuộc sống của bạn có thật sự 'tốt' như bạn vẫn thể hiện ra không?",
"B019$Bạn có một nỗi sợ hãi 'vô lý' nào không?",
"B020$Bạn đã từng 'ăn cắp' tiền của bố mẹ chưa?",
"B021$Bạn đã bao giờ giả vờ bị ốm để trốn việc/trốn học chưa?",
"B022$Nếu có thể biến một thứ bất kỳ thành món tráng miệng, bạn sẽ chọn cái gì?",
"B023$Nếu có thể 'tẩy não' một kỷ niệm trong quá khứ, bạn sẽ xóa đi kỷ niệm nào?",
"B024$Bạn có một 'khuất tất' nào đó về quá khứ không?",
"B025$Bạn đã từng 'phá hoại' một mối quan hệ nào đó của người khác chưa?",
"B026$Bạn có bao giờ 'quan hệ' với người cùng giới chưa?",
"B027$Bạn đã từng 'quan hệ' với người 'có quan hệ' với bạn bè của bạn chưa?",
"B028$Bạn có bao giờ 'tống tiền' người khác chưa?",
"B029$Bạn có bao giờ 'lén lút' nghe lén cuộc trò chuyện của người khác chưa?",
"B030$Nếu bạn đột nhiên trở thành người duy nhất trên Trái Đất, bạn sẽ làm gì?",
"B031$Bạn có một 'cách' để 'được lòng' người khác không?",
"B032$Bí mật nào bạn chưa từng kể với ai trong nhóm?",
"B033$Bạn có một 'bí mật' nào đó liên quan đến pháp luật không?",
"B034$Lần bạn làm 'quê' người khác trước mặt đám đông là khi nào?",
"B035$Bạn đã bao giờ phải lòng một nhân vật hư cấu trong phim hoặc sách chưa?",
"B036$Kể về một lần bạn làm một điều gì đó ngu ngốc chỉ vì bị thách đố.",
"B037$Bạn có tin vào lời nguyền không?",
"B038$Bạn có một 'nguyên tắc' nào về tình yêu không bao giờ phá vỡ không?",
"B039$Bạn có một bí mật 'lớn' nào về người yêu cũ của bạn không?",
"B040$Bạn có một sở thích 'đặc biệt' nào mà bạn không muốn ai biết không?",
"B041$Bạn có bao giờ 'tấn công' một người nào đó chưa?",
"B042$Bạn có bao giờ 'nói xấu' một người nào đó ngay trước mặt họ chưa?",
"B043$Nếu có thể đổi chỗ cho một người khác trong một ngày, bạn sẽ chọn ai?",
"B044$Bạn có bao giờ 'tưởng tượng' mình là một người 'tồi tệ' không?",
"B045$Bạn có từng nói dối bạn bè để được đi chơi với người bạn thích chưa?",
"B046$Bạn đã từng làm điều gì điên rồ nhất để gây ấn tượng với một người bạn thích?",
"B047$Lần cuối cùng bạn 'ghen' với một người khác là khi nào?",
"B048$Bạn đã bao giờ phải lòng một người đã có người yêu chưa?",
"B049$Bạn có bao giờ 'thích' một người mà bạn biết họ có 'vấn đề' chưa?",
"B050$Bạn đã bao giờ 'thích' một người vì 'gu' âm nhạc của họ chưa?",
`_Kiêu_Ngạo_.School.B$Khi nào bạn đã công khai cười nhạo ước mơ của một bạn học vì bạn nghĩ chúng quá ngây thơ hoặc kém cỏi?`,
`___None____.School.B$Ai là người mà bạn đã "sửa đổi" hồ sơ học tập của họ bằng cách thêm những lời nhận xét tiêu cực không đúng sự thật?`,
`_Phẫn_Nộ___.School.B$Bạn đã từng cố tình kích động một cuộc ẩu đả giữa hai người bạn chỉ để xem họ đánh nhau chưa?`,
`___None____.School.B$Điều gì là lời nói dối bạn đã "thích nghi" liên tục trong nhiều năm để che đậy một sự cố lớn bạn gây ra?`,
`_Tham_Lam__.School.B$Bạn có từng đe dọa tố cáo một hành vi sai trái của người khác để kiếm tiền hoặc lợi ích từ họ không?`,
`___None____.School.B$"Ở đâu" bạn đã "loại bỏ" các quy tắc của trường một cách có chủ đích để thực hiện một hành vi nguy hiểm (ví dụ: trèo tường)?`,
`__Dâm_Dục__.School.B$Bạn đã "tận dụng" sự tin tưởng của một thành viên trong hội đồng học sinh để nắm được thông tin nội bộ rồi lạm dụng nó như thế nào?`,
`_Phẫn_Nộ___.School.B$Điều gì là sự kiện của trường mà bạn đã "thay thế" nội dung bằng những hình ảnh hoặc thông điệp xúc phạm để trả thù?`,
`___None____.School.B$Tại sao bạn lại "kết hợp" những lời đe dọa về thể chất và tinh thần để ép buộc người khác làm một điều vi phạm pháp luật?`,
`_Tham_Lam__.School.B$Ai là người bạn đã dụ dỗ làm chứng gian trong một cuộc điều tra nghiêm trọng của trường để bảo vệ bản thân?`,
`___None____.School.B$Bạn có cố tình "loại bỏ" bằng chứng về sự vô tội của một người bạn học khi họ bị cáo buộc sai không?`,
`_Kiêu_Ngạo_.School.B$Bạn đã "tận dụng" sự thiếu hiểu biết của giáo viên mới như thế nào để thao túng kết quả của cả một học kỳ?`,
`___None____.School.B$Bạn đã "đảo ngược" lại sự thật về một vụ trộm nghiêm trọng trong trường bằng cách nào để biến người bị hại thành kẻ tình nghi?`,
`__Dâm_Dục__.School.B$"Ở đâu" bạn đã sắp xếp một cuộc gặp bí mật với người có quyền lực (ví dụ: giáo viên) để đổi lấy đặc quyền?`,
`___None____.School.B$Khi nào bạn đã "thích nghi" với một quy tắc chống gian lận mới bằng cách tạo ra một hệ thống gian lận tinh vi hơn cho cả lớp?`,
`_Phẫn_Nộ___.School.B$Điều gì là thông tin cá nhân của một giáo viên mà bạn đã "sửa đổi" (giả mạo) để hạ uy tín của họ trước nhà trường?`,
`___None____.School.B$Ai là người bạn đã "thay thế" vai trò thủ phạm bằng cách đe dọa họ nhận tội thay cho bạn trong một vụ việc nghiêm trọng?`,
`_Kiêu_Ngạo_.Social.B$Khi nào bạn đã công khai cười nhạo và đăng lại bài đăng cũ, ngây thơ của một người bạn để thể hiện sự tiến bộ của mình?`,
`___None____.Social.B$Ai là người bạn đã "sửa đổi" câu chuyện bịa đặt để khiến họ bị cộng đồng mạng tẩy chay?`,
`_Phẫn_Nộ___.Social.B$Bạn đã từng tạo một hội nhóm kín để cùng nhau nói xấu và lăng mạ một người cụ thể chưa?`,
`___None____.Social.B$Điều gì là trend nguy hiểm hoặc vi phạm đạo đức mà bạn đã "thích nghi" để làm theo chỉ vì muốn câu tương tác?`,
`_Tham_Lam__.Social.B$Bạn có từng lập kế hoạch lừa đảo chi tiết để lấy mã thẻ quà tặng hoặc thông tin tài khoản ngân hàng của người lạ không?`,
`___None____.Social.B$"Ở đâu" bạn đã "loại bỏ" các bằng chứng về việc mình từng có mối quan hệ với một người không còn nổi tiếng để bảo vệ danh tiếng hiện tại?`,
`__Dâm_Dục__.Social.B$Bạn đã "tận dụng" hình ảnh cá nhân quyến rũ như thế nào để thao túng một người quản lý/nhân viên cấp cao có quyền lực trên mạng?`,
`_Phẫn_Nộ___.Social.B$Điều gì là bằng chứng bạn đã "thay thế" để buộc tội một người vô tội đã phát tán thông tin độc hại mà thực chất là do bạn làm?`,
`___None____.Social.B$Tại sao bạn lại "kết hợp" kỹ năng lập trình với thông tin cá nhân của người khác để tạo ra một chiến dịch phishing (lừa đảo) quy mô lớn?`,
`_Tham_Lam__.Social.B$Ai là người bạn đã dụ dỗ làm công cụ để đánh cắp dữ liệu mật từ một công ty hoặc tổ chức trên mạng?`,
`___None____.Social.B$Bạn có cố tình "loại bỏ" (hack và xóa) tài khoản xã hội của một người bạn để chấm dứt sự nghiệp online của họ không?`,
`_Kiêu_Ngạo_.Social.B$Bạn đã "tận dụng" những sai sót về an ninh mạng của một nền tảng xã hội như thế nào để đọc trộm tin nhắn riêng của người khác?`,
`___None____.Social.B$Bạn đã "đảo ngược" lại sự thật về một vụ xâm phạm quyền riêng tư nghiêm trọng bằng cách nào để biến nạn nhân thành người đồng lõa?`,
`__Dâm_Dục__.Social.B$"Ở đâu" bạn đã thiết lập một trang web hoặc nhóm ẩn danh để trao đổi thông tin nhạy cảm (ảnh, video) mà không có sự đồng ý của nạn nhân?`,
`___None____.Social.B$Khi nào bạn đã "thích nghi" bằng cách làm giả các tài liệu pháp lý (ví dụ: lệnh cấm) và đăng lên mạng để đe dọa người khác?`,
`_Phẫn_Nộ___.Social.B$Điều gì là bằng chứng (ảnh, video) bạn đã "sửa đổi" một cách tinh vi để hủy hoại hoàn toàn uy tín chuyên môn của một người?`,
`___None____.Social.B$Ai là người bạn đã "thay thế" danh tính bằng cách giả mạo họ trên mạng để thực hiện các hành vi phạm pháp?`,
`_Kiêu_Ngạo_.Funk.B$Khi nào bạn đã công khai cười nhạo nỗi sợ hãi thầm kín của một người bạn?`,
`___None____.Funk.B$Ai là người mà bạn đã "sửa đổi" câu chuyện để khiến họ bị gia đình/bạn bè xa lánh vì một nỗi sợ không có thật?`,
`_Phẫn_Nộ___.Funk.B$Bạn đã từng cố tình kích động một cuộc xung đột giữa hai người bạn chỉ vì bạn sợ họ hợp tác chống lại bạn chưa?`,
`___None____.Funk.B$Điều gì là lời nói dối bạn đã "thích nghi" liên tục trong nhiều năm để che đậy một hành động sợ hãi lớn bạn gây ra?`,
`_Tham_Lam__.Funk.B$Bạn có từng đe dọa tiết lộ một nỗi sợ lớn của người khác để kiếm tiền hoặc lợi ích từ họ không?`,
`___None____.Funk.B$"Ở đâu" bạn đã "loại bỏ" các bằng chứng về việc bạn từng hứa sẽ giúp một người đang sợ hãi?`,
`__Dâm_Dục__.Funk.B$Bạn đã "tận dụng" sự tin tưởng của một người bạn như thế nào để nắm được nỗi sợ của họ rồi lạm dụng nó?`,
`_Phẫn_Nộ___.Funk.B$Điều gì là bằng chứng bạn đã "thay thế" (làm giả) để buộc tội một người vô tội đã đe dọa bạn, trong khi bạn mới là người gây ra nỗi sợ hãi?`,
`___None____.Funk.B$Tại sao bạn lại "kết hợp" các lời đe dọa về thể chất và tinh thần để ép buộc người khác làm một điều vi phạm pháp luật mà họ sợ hãi?`,
`_Tham_Lam__.Funk.B$Ai là người bạn đã dụ dỗ làm chứng gian trong một vụ kiện nghiêm trọng vì sợ bị bạn làm hại?`,
`___None____.Funk.B$Bạn có cố tình "loại bỏ" bằng chứng về sự vô tội của một người bị cáo buộc vì sợ họ sẽ trả thù bạn nếu được minh oan không?`,
`_Kiêu_Ngạo_.Funk.B$Bạn đã "tận dụng" nỗi sợ thất bại của người khác như thế nào để thao túng kết quả của cả một dự án lớn?`,
`___None____.Funk.B$Bạn đã "đảo ngược" lại sự thật về một vụ tai nạn bằng cách nào để biến nạn nhân thành thủ phạm vì sợ bị kiện?`,
`__Dâm_Dục__.Funk.B$"Ở đâu" bạn đã sắp xếp một cuộc gặp bí mật với người có quyền lực để đổi lấy đặc quyền bằng cách đe dọa?`,
`___None____.Funk.B$Khi nào bạn đã "thích nghi" bằng cách làm giả hồ sơ sức khỏe tâm thần của người khác để họ bị cô lập vì sợ họ vượt trội hơn bạn?`,
`_Phẫn_Nộ___.Funk.B$Điều gì là tài liệu mật của công ty mà bạn đã "sửa đổi" (giả mạo) để hủy hoại danh tiếng của một người mà bạn sợ hãi?`,
`___None____.Funk.B$Ai là người bạn đã "thay thế" vai trò thủ phạm bằng cách đe dọa họ nhận tội thay cho bạn trong một vụ việc nghiêm trọng?`,

"A001$Món đồ lót màu gì bạn thấy 'sexy' nhất?",
"A002$Lần cuối cùng bạn 'thèm khát' ai đó là khi nào?",
"A003$Nếu được tặng một bộ đồ ngủ, bạn muốn nó 'thiếu vải' hay 'kín đáo'?",
"A004$Đâu là điều 'tồi tệ' nhất bạn đã làm trong một mối quan hệ?",
"A005$Lần bạn 'phạm' một điều luật 'quan trọng' là khi nào?",
"A006$Nếu được 'đổi' một điều về cuộc đời mình, bạn sẽ đổi điều gì?",
"A007$Bạn đã từng 'bị' lừa đảo qua mạng xã hội chưa?",
"A008$Bạn đã bao giờ nghĩ đến chuyện ngoại tình chưa? Nếu có, vì sao?",
"A009$Bạn nghĩ nụ hôn ở đâu trên cơ thể là 'điên' nhất?",
"A010$Bạn có nghĩ mình 'hấp dẫn' không?",
"A011$Bạn có một thói quen 'kỳ lạ' nào liên quan đến tình yêu không?",
"A012$Bạn nghĩ gì về 'tình yêu' qua 'tình một đêm'?",
"A013$Kể về một lần bạn bị tổn thương sâu sắc trong tình yêu.",
"A014$Kể về lần đầu tiên bạn hôn ai đó.",
"A015$Bạn đã bao giờ “yêu” ai đó mà họ lại không yêu bạn chưa? Kể về cảm xúc lúc đó.",
"A016$Bạn có bao giờ 'lén lút' nghe lén cuộc trò chuyện của người khác chưa?",
"A017$Điều gì ở người bạn đời cũ khiến bạn nhớ nhất (về cả mặt cảm xúc lẫn thể xác)?",
"A018$Bạn có một 'cách' để quyến rũ người khác không?",
"A019$Bạn nghĩ mình có thể 'chiều' người yêu đến mức nào?",
"A020$Bạn có một 'cách' để 'được lòng' người khác không?",
"A021$Bạn có từng 'thao túng tâm lý' (manipulate) người yêu để đạt được điều mình muốn không?",
"A022$Bạn có 'ám ảnh' với người yêu cũ không? Nếu có, vì sao?",
"A023$Bạn sẽ phản ứng thế nào nếu người yêu bạn yêu cả hai giới?",
"A024$Bạn thích được 'vuốt ve' ở đâu nhất?",
"A025$Bạn thích được 'thủ thỉ' điều gì vào tai?",
"A026$Bạn có một 'bí mật' nào đó về tình dục mà bạn chưa kể cho ai không?",
"A027$Bạn có tin vào lời nguyền không?",
"A028$Bạn có một 'nguyên tắc' nào về tình yêu không bao giờ phá vỡ không?",
"A029$Bạn có bao giờ cảm thấy thiếu tự tin về cơ thể của mình trước người yêu/bạn tình chưa?",
"A030$Đâu là vị trí 'thích' của bạn khi ngủ cùng người ấy?",
"A031$Bạn có một bí mật 'lớn' nào về người yêu cũ của bạn không?",
"A032$Bạn có 'khao khát' được hôn một người nào đó trong nhóm này không?",
"A033$Bạn có nghĩ mình là một người 'tốt' trên giường không?",
"A034$Bạn có bao giờ 'nói xấu' một người nào đó ngay trước mặt họ chưa?",
"A035$Bạn có bao giờ 'tưởng tượng' mình là một người 'tồi tệ' không?",
"A036$Lần cuối cùng bạn 'ghen' với một người khác là khi nào?",
"A037$Bạn đã bao giờ 'thích' một người vì mùi hương cơ thể của họ chưa?",
"A038$Bạn có bao giờ 'thích' một người mà bạn biết họ có 'vấn đề' chưa?",
"A039$Cảm giác yêu thầm một người bạn thân là như thế nào?",
"A040$Bạn đã bao giờ 'thích' một người vì 'gu' âm nhạc của họ chưa?",
`_Tham_Lam__.School.A$Bạn có từng cố ý làm hỏng hồ sơ nộp đơn đại học của một người mà bạn coi là đối thủ không?`,
`___None____.School.A$Bạn đã "loại bỏ" vai trò của mình trong việc gây ra chấn thương cho một bạn học như thế nào?`,
`___Đố_Kị___.School.A$Tại sao bạn lại "đảo ngược" mối quan hệ với một người hướng dẫn quan trọng (mentor) bằng cách tố cáo họ một cách sai sự thật?`,
`___None____.School.A$"Ở đâu" bạn đã "kết hợp" việc trốn thoát khỏi trường với hành vi phá hoại tài sản công có chủ đích?`,
`__Dâm_Dục__.School.A$Ai là người mà bạn đã hứa hẹn về mặt tài chính hoặc xã hội để họ làm hại một người khác theo yêu cầu của bạn?`,
`___None____.School.A$Điều gì là bí mật của một bạn học mà bạn đã "tận dụng" để tống tiền họ?`,
`_Kiêu_Ngạo_.School.A$Bạn có "sửa đổi" một bức ảnh của trường để khiến một người trông đáng sợ/kỳ quái nhằm mục đích bắt nạt có hệ thống không?`,
`___None____.School.A$Bạn đã "thích nghi" bằng cách liên tục nói dối về tình trạng tài chính của mình để nhận sự giúp đỡ (học bổng, quà tặng) mặc dù bạn không cần nó không?`,
`_Phẫn_Nộ___.School.A$Khi nào bạn đã sử dụng thông tin từ hệ thống máy tính của trường để truy cập trái phép vào tài khoản của người khác?`,
`___None____.School.A$Tại sao bạn lại "thay thế" sự trung thực của mình bằng việc trở thành một "con rối" cho một nhóm có quyền lực để đạt được mục tiêu cá nhân?`,
`_Tham_Lam__.School.A$Ai là người bạn đã buộc phải từ bỏ một cơ hội học tập có giá trị (ví dụ: du học) chỉ vì bạn muốn cơ hội đó?`,
`___None____.School.A$Điều gì là hồ sơ học tập của bạn mà bạn đã cố tình "loại bỏ" khỏi hệ thống để che giấu một hành vi sai trái nghiêm trọng?`,
`___Đố_Kị___.School.A$Bạn có từng cố gắng kích động sự thù ghét của cả lớp đối với một bạn học mới để họ phải chuyển trường không?`,
`___None____.School.A$Bạn đã "kết hợp" lời đe dọa với một món quà để ép buộc người khác phải im lặng về sự thật tàn nhẫn của bạn như thế nào?`,
`_Kiêu_Ngạo_.School.A$"Ở đâu" bạn đã "tận dụng" đức tin/lòng tốt của một thầy cô giáo để lừa dối họ và làm hại một bạn học khác?`,
`_Tham_Lam__.Social.A$Bạn có từng cố ý làm rò rỉ thông tin cá nhân nhạy cảm của người khác (doxxing) để kiếm tiền hoặc đổi lấy lợi ích?`,
`___None____.Social.A$Bạn đã "loại bỏ" sự thật về một sai lầm lớn của mình như thế nào bằng cách tạo ra một câu chuyện giả về khủng hoảng sức khỏe trên mạng?`,
`___Đố_Kị___.Social.A$Tại sao bạn lại "đảo ngược" lời nói của mình để tuyên bố rằng một người bạn đang bị tâm thần hoặc không đáng tin cậy chỉ vì họ thành công hơn?`,
`___None____.Social.A$"Ở đâu" bạn đã "kết hợp" các công cụ tạo tin nhắn giả với công cụ chỉnh sửa ảnh để tạo ra bằng chứng giả về tội lỗi của người khác?`,
`__Dâm_Dục__.Social.A$Ai là người có quyền lực mà bạn đã dụ dỗ để họ thao túng các chính sách hoặc thuật toán của nền tảng xã hội cho lợi ích của bạn?`,
`___None____.Social.A$Điều gì là thông tin nội bộ của công ty/tổ chức mà bạn đã "tận dụng" để gây hoang mang dư luận và thao túng thị trường chứng khoán?`,
`_Kiêu_Ngạo_.Social.A$Bạn có "sửa đổi" một đoạn âm thanh/cuộc gọi của người khác để biến lời nói vô tội thành lời thú tội về hành vi sai trái không?`,
`___None____.Social.A$Bạn đã "thích nghi" bằng cách nào để liên tục tránh bị blacklist (cấm) khỏi các nền tảng mạng xã hội mặc dù bạn liên tục vi phạm chính sách?`,
`_Phẫn_Nộ___.Social.A$Khi nào bạn đã sử dụng tài khoản giả để công khai gửi các tin nhắn đe dọa tính mạng/làm hại tới một cá nhân?`,
`___None____.Social.A$Tại sao bạn lại "thay thế" danh tính của mình bằng một nhóm ẩn danh để thực hiện hành vi trolling (chọc phá) có tổ chức, nhằm gây rối loạn một cộng đồng?`,
`_Tham_Lam__.Social.A$Ai là người bạn đã ép buộc phải rút đơn kiện hoặc xin lỗi công khai trên mạng để bạn không bị mất hợp đồng quảng cáo béo bở?`,
`___None____.Social.A$Điều gì là thông tin về quá khứ đen tối của bạn mà bạn đã trả tiền để "loại bỏ" khỏi Internet (Right to be forgotten)?`,
`___Đố_Kị___.Social.A$Bạn có từng trả tiền để thuê người tấn công và làm sập trang web/tài khoản bán hàng của đối thủ cạnh tranh không?`,
`___None____.Social.A$Bạn đã "kết hợp" các trang deep-fake với tài khoản giả để tạo ra bằng chứng giả về mối quan hệ bất chính của một người có ảnh hưởng như thế nào?`,
`_Kiêu_Ngạo_.Social.A$"Ở đâu" bạn đã "tận dụng" công cụ phân tích dữ liệu lớn để tìm kiếm và bóc mẽ mọi sai sót nhỏ nhất của người bạn ghét để hủy hoại họ?`,
`_Tham_Lam__.Funk.A$Bạn có từng cố ý làm hỏng hồ sơ nộp đơn của người khác vì sợ họ sẽ thành công hơn và bạn sẽ bị lu mờ không?`,
`___None____.Funk.A$Bạn đã "loại bỏ" vai trò của mình trong việc gây ra chấn thương tâm lý nghiêm trọng cho một người bạn như thế nào?`,
`___Đố_Kị___.Funk.A$Tại sao bạn lại "đảo ngược" lại sự thật, cáo buộc một người là kẻ nói dối chỉ vì sợ bị họ phanh phui sự thật về bạn?`,
`___None____.Funk.A$"Ở đâu" bạn đã "kết hợp" các công cụ mạng xã hội giả với thông tin cá nhân của người khác để tạo ra một chiến dịch bắt nạt có hệ thống?`,
`__Dâm_Dục__.Funk.A$Ai là người mà bạn đã hứa hẹn về mặt tài chính/xã hội để họ làm hại một người khác mà bạn sợ hãi?`,
`___None____.Funk.A$Điều gì là sự kiện đau buồn trong quá khứ của người khác mà bạn đã "tận dụng" để tống tiền họ?`,
`_Kiêu_Ngạo_.Funk.A$Bạn có "sửa đổi" một đoạn âm thanh/cuộc gọi của người khác để khiến họ trông có vẻ đang sợ hãi hoặc sắp tự tử, nhằm mục đích thao túng?`,
`___None____.Funk.A$Bạn đã "thích nghi" bằng cách nào để liên tục nói dối về việc bạn bị người khác đe dọa nhằm thu hút sự bảo vệ từ người có quyền lực?`,
`_Phẫn_Nộ___.Funk.A$Khi nào bạn đã sử dụng thông tin từ hệ thống máy tính để gửi các tin nhắn đe dọa tính mạng tới một cá nhân?`,
`___None____.Funk.A$Tại sao bạn lại "thay thế" danh tính của mình bằng một nhóm ẩn danh để đe dọa và gây rối loạn một cộng đồng?`,
`_Tham_Lam__.Funk.A$Ai là người bạn đã ép buộc phải từ bỏ cơ hội nghề nghiệp có giá trị để bạn không tiết lộ một bí mật tàn nhẫn về họ?`,
`___None____.Funk.A$Điều gì là hồ sơ/bằng chứng chứng minh tội lỗi của bạn mà bạn đã trả tiền để "loại bỏ" khỏi mọi hệ thống vì sợ bị bắt?`,
`___Đố_Kị___.Funk.A$Bạn có từng trả tiền để thuê người tấn công và phá hoại cuộc sống của một người vì sợ họ thành công hơn bạn không?`,
`___None____.Funk.A$Bạn đã "kết hợp" lời hứa về sự an toàn giả tạo với hành vi bạo lực tinh thần có hệ thống như thế nào để giữ người khác bên cạnh vì sợ hãi?`,
`_Kiêu_Ngạo_.Funk.A$"Ở đâu" bạn đã "tận dụng" sự ngây thơ của người khác để khiến họ tin rằng mọi hành vi đe dọa và kiểm soát của bạn là bảo vệ họ khỏi nỗi sợ?`,

"X.X$Màu áoót mà bạn đang mặc?---Nam miễn!!!",
"X.X$Màu quầ lót mà bạn đang mặc?---Nam miễn!!!",
"X.X$Màu quầ lót mà bạn đang mặc?---Nữ miễn!!!",
"SX.X$Bạn đã bao giờ tò mò về tinh dịch của bản thân có vị gì chưa?!!!",
"SX.X$Nếu bắt buộc lựa chọn, bạn sẽ chọn làm BedBoy hay BadBoy?!!!",
"SX.X$Vào đêm cặp đôi của bạn, bạn sẽ lựa chọn không gian thoáng hay trong phòng?!!!",
"SX.X$Tên người mà bạn mơ thấy khi mộng tinh?!!!",
"SX.X$Bạn có nghĩ mình là người hôn giỏi không?!!!",
"SX.X$Bạn có cảm giác thèm khát ôm crush từ đằng sau dù chẳng là gì chưa?---Nữ miễn!!!",
"SX.X$Bạn có cảm giác thèm khát ôm crush từ đằng sau dù chẳng là gì chưa?---Nam miễn!!!",
"SX.X$Đối với bạn, ham muốn sẽ đứng thứ mấy trong một mối quan hệ đẫ và đang trải qua?!!!",
"SX.X$Bạn cảm nhận chỗ đó của bạn có mùi như thế nào?---Nam miễn!!!",
"SX.X$Bạn cảm nhận chỗ đó của bạn có mùi như thế nào?---Nữ miễn!!!",
"SX.X$Bạn thấy phần lông chỗ đó của bạn như nào?---Nữ miễn!!!",
"SX.X$Bạn thấy phần lông chỗ đó của bạn như nào?---Nam miễn!!!",
"SX.X$Bạn muốn cùng ai trong nhóm này xem phim heo?!!!",
"SX.X$Chỗ đó của bạn dài bao nhiêu?---Nữ miễn!!!",
"SX.X$Cảm giác hôn môi người mình yêu như thế nào?!!!",
"SX.X$Bạn bắt đầu cảm thấy muốn làm chuyện đó với người mình thích vào năm nào?!!!",
"SX.X$Loại đồ ngủ mà bạn cảm thấy thú thú nhất khi người yêu hoặc crush mình mặc?!!!",
"SX.X$Bạn có cạo lông chỗ đó không?---Nam miễn!!!",
"SX.X$Bạn có cạo lông chỗ đó không?---Nữ miễn!!!",
"SX.X$Màu áo lót mà bạn đang mặc?---Nam miễn!!!",
"SX.X$Màu quần lót mà bạn đang mặc?---Nam miễn!!!",
"SX.X$Màu quần lót mà bạn đang mặc?---Nữ miễn!!!",
"SX.X$Bạn đã bao giờ tò mò về tinh dịch của bản thân có vị gì chưa?!!!",
"SX.X$Nếu bắt buộc lựa chọn, bạn sẽ chọn làm BedBoy hay BadBoy?!!!",
"SX.X$Vào đêm cặp đôi của bạn, bạn sẽ lựa chọn không gian thoáng hay trong phòng?!!!",
"SX.X$Tên người mà bạn mơ thấy khi mộng tinh?!!!",
"SX.X$Bạn có nghĩ mình là người hôn giỏi không?!!!",
"SX.X$Bạn có cảm giác thèm khát ôm crush từ đằng sau dù chẳng là gì chưa?---Nữ miễn!!!",
"SX.X$Bạn có cảm giác thèm khát ôm crush từ đằng sau dù chẳng là gì chưa?---Nam miễn!!!",
"SX.X$Đối với bạn, ham muốn sẽ đứng thứ mấy trong một mối quan hệ đẫ và đang trải qua?!!!",
"SX.X$Bạn cảm nhận chỗ đó của bạn có mùi như thế nào?---Nam miễn!!!",
"SX.X$Bạn cảm nhận chỗ đó của bạn có mùi như thế nào?---Nữ miễn!!!",
"SX.X$Bạn thấy phần lông chỗ đó của bạn như nào?---Nữ miễn!!!",
"SX.X$Bạn thấy phần lông chỗ đó của bạn như nào?---Nam miễn!!!",
"SX.X$Bạn muốn cùng ai trong nhóm này xem phim heo?!!!",
"SX.X$Chỗ đó của bạn dài bao nhiêu?---Nữ miễn!!!",
"SX.X$Cảm giác hôn môi người mình yêu như thế nào?!!!",
"SX.X$Bạn bắt đầu cảm thấy muốn làm chuyện đó với người mình thích vào năm nào?!!!",
"SX.X$Loại đồ ngủ mà bạn cảm thấy thú thú nhất khi người yêu hoặc crush mình mặc?!!!",
"SX.X$Bạn có cạo lông chỗ đó không?---Nam miễn!!!",
"SX.X$Bạn có cạo lông chỗ đó không?---Nữ miễn!!!",
]