let QUESTION_TRUTH = [
"F001$Món ăn bạn thích nhất là gì?",
"F002$Nếu có thể trở thành một loài động vật, bạn muốn là con gì?",
"F003$Bạn có tin vào ma quỷ không?",
"F004$Đồ vật giá trị nhất bạn đang sở hữu là gì?",
"F005$Bộ phim hoạt hình yêu thích nhất của bạn là gì?",
"F006$Bạn có bao giờ nói dối bố mẹ chưa?",
"F007$Bạn đã từng thích thầm một ai đó chưa?",
"F008$Kỉ niệm đáng nhớ nhất thời thơ ấu của bạn là gì?",
"F009$Nếu trúng số độc đắc, bạn sẽ làm gì đầu tiên?",
"F010$Bài hát yêu thích nhất của bạn là gì?",
"F011$Bạn có một biệt danh nào 'ngớ ngẩn' không?",
"F012$Bạn có thể ngủ ở bất cứ đâu không?",
"F013$Điều bạn tự hào nhất về bản thân là gì?",
"F014$Bạn sợ con vật gì nhất?",
"F015$Bạn có từng ăn cắp vặt gì chưa?",
"F016$Nếu bạn có thể sở hữu một siêu năng lực, bạn muốn có năng lực gì?",
"F017$Bạn đã bao giờ thử ăn một món ăn 'kinh dị' nào đó chưa?",
"F018$Bạn có một thói quen 'lạ' nào khi ở một mình không?",
"F019$Điều gì khiến bạn 'xấu hổ' nhất khi ở cùng người lạ?",
"F020$Bạn có tin vào người ngoài hành tinh không?",
"F021$Bộ phim hoặc cuốn sách khiến bạn khóc nhiều nhất là gì?",
"F022$Bạn có một bí mật 'ngớ ngẩn' nào liên quan đến idol của mình không?",
"F023$Nếu bạn là một nhân vật hoạt hình, bạn muốn là ai?",
"F024$Bạn có bao giờ 'tưởng tượng' mình là một ca sĩ/diễn viên nổi tiếng chưa?",
"F025$Bạn có thể kể về lần đầu tiên đi máy bay/tàu hỏa của mình không?",
"F026$Bạn có thể nói một từ 'bí mật' mà chỉ bạn và người thân biết không?",
"F027$Món đồ 'vô dụng' nhất bạn từng mua là gì?",
"F028$Điều bạn làm khi 'cực kỳ' buồn chán là gì?",
"F029$Bạn đã bao giờ 'thích' một người vì tính cách hài hước của họ chưa?",
"F030$Nếu có thể quay ngược thời gian 1 giờ, bạn sẽ làm gì?",
"F031$Kể tên một thói quen xấu nhất mà bạn đang cố gắng từ bỏ.",
"F032$Nếu có thể quay ngược thời gian, bạn muốn thay đổi điều gì trong quá khứ?",
"F033$Điều gì khiến bạn cảm thấy tự hào nhất về bản thân?",
"F034$Kể một bí mật thời thơ ấu mà chưa ai biết.",
"F035$Mô tả 3 từ về con người thật của bạn mà người khác có thể không nhận ra.",
"F036$Nếu có thể sống trong một bộ phim, bạn sẽ chọn bộ phim nào và vào vai ai?",
"F037$Bạn đã bao giờ nói dối để thoát khỏi một rắc rối lớn chưa?",
"F038$Kể về lần đầu tiên bạn say rượu (nếu có).",
"F039$Nếu bạn có một triệu đô la, bạn sẽ làm gì với nó?",
"F040$Điều gì là thử thách lớn nhất bạn từng đối mặt?",
"F041$Nếu phải đánh đổi một điều gì đó quan trọng nhất để có được tiền bạc, bạn sẽ đánh đổi điều gì?",
"F042$Bạn đã bao giờ dùng tiền để giải quyết một rắc rối lớn chưa?",
"F043$Bạn có sẵn sàng 'đạp lên' người khác để đạt được mục tiêu của mình không?",
"F044$Điều gì là động lực lớn nhất của bạn trong công việc?",
"F045$Kể về một lần bạn tiêu tiền một cách vô nghĩa nhưng lại cảm thấy rất hài lòng.",
"F046$Nếu bạn có thể tàng hình trong một ngày, điều đầu tiên bạn sẽ làm là gì?",
"F047$Loại nhạc nào khiến bạn xấu hổ nhất khi nghe?",
"F048$Bạn thích nhất điều gì ở bản thân mình?",
"F049$Điều gì khiến bạn khó chịu nhất?",
"F050$Lần cuối cùng bạn nói dối là khi nào?",
"F051$Lần đầu tiên bạn bị 'thất tình' là khi nào?",
"F052$Điều gì ở một người bạn khiến bạn khó chịu nhất nhưng bạn vẫn chấp nhận được?",
"F053$Nếu phải chọn một người trong nhóm làm 'em bé' để chăm sóc trong một ngày, bạn sẽ chọn ai?",
"F054$Bạn đã bao giờ nói 'tôi yêu bạn' với một người bạn thân chưa?",
"F055$Điều gì ở người khác mà bạn ngưỡng mộ nhất?",
"F056$Bạn đã từng 'để ý' đến một người bạn thân chưa?",
"F057$Điều gì bạn nghĩ là 'tệ' nhất khi bạn có một người bạn trai/bạn gái?",
"F058$Món quà ý nghĩa nhất bạn từng nhận được từ một người bạn là gì?",
"F059$Điều gì khiến bạn cảm thấy an toàn và thoải mái khi ở bên cạnh ai đó?",
"F060$Nếu có thể trở lại quá khứ để thay đổi một điều về mối quan hệ của bạn với một người nào đó, bạn sẽ thay đổi điều gì?",
"F061$Nếu có thể biến một thứ bất kỳ thành món tráng miệng, bạn sẽ chọn cái gì?",
"F062$Bạn đã từng làm đổ thứ gì vào người khác một cách 'cực kỳ xấu hổ' chưa?",
"F063$Nếu phải mặc một bộ trang phục của nhân vật hoạt hình trong một tuần, bạn sẽ chọn ai?",
"F064$Bạn đã bao giờ nhặt được tiền trên đường chưa? Nếu có, bạn làm gì với nó?",
"F065$Bạn có từng 'lục lọi' điện thoại của ai đó chưa?",
"F066$Lần bạn 'quê độ' nhất trước mặt người lạ là khi nào?",
"F067$Món đồ nào trong nhà bạn 'quý' đến mức không ai được đụng vào?",
"F068$Bạn đã bao giờ phải lòng một nhân vật hư cấu chưa?",
"F069$Nếu có một người theo dõi bạn cả ngày và ghi lại mọi việc bạn làm, họ sẽ thấy điều gì bất ngờ nhất?",
"F070$Bạn có từng ngủ gật ở một nơi công cộng nào đó chưa?",
"F071$Điều gì khiến bạn cười nhiều nhất?",
"F072$Bạn đã bao giờ nói dối rằng mình đã xem một bộ phim hoặc một cuốn sách nào đó để 'hợp' với mọi người chưa?",
"F073$Bạn thích tắm vòi sen hay tắm bồn hơn?",
"F074$Nếu bạn có thể 'tăng tốc' thời gian khi làm một việc, đó là việc gì?",
"F075$Bạn sẽ làm gì nếu bạn đột nhiên trở thành người duy nhất trên Trái Đất?",
"F076$Nếu có thể đổi chỗ cho một người nổi tiếng bất kỳ trong một ngày, bạn sẽ chọn ai?",
"F077$Kỹ năng vô dụng nhất mà bạn từng học là gì?",
"F078$Nếu tiền không phải là vấn đề, bạn sẽ làm gì mỗi ngày?",
"F079$Bạn thích bị mắc kẹt ở một hòn đảo hoang với ai nhất trong nhóm chúng ta?",
"F080$Nếu bạn có thể 'tẩy não' một kỷ niệm trong quá khứ, bạn sẽ xóa đi kỷ niệm nào?",
"F081$Bí mật nào bạn chưa từng kể với ai trong nhóm?",
"F082$Nếu một ngày bạn thức dậy và có thể nói chuyện với động vật, con vật đầu tiên bạn muốn trò chuyện là gì?",
"F083$Bạn có 'tật xấu' nào mà bạn bè không biết không?",
"F084$Nếu được chọn một siêu năng lực, bạn sẽ chọn gì và dùng nó để làm gì?",
"F085$Bạn có từng 'sáng tác' ra một câu chuyện hoặc một lời nói dối chỉ để thoát khỏi rắc rối chưa?",
"F086$Lần cuối cùng bạn khóc là vì chuyện gì?",
"F087$Bạn thích nhận quà bất ngờ hay được hỏi trước khi mua hơn?",
"F088$Bạn có tin vào ma quỷ hay những điều siêu nhiên không?",
"F089$Bạn cảm thấy 'tội lỗi' nhất khi làm điều gì?",
"F090$Điều gì khiến bạn cảm thấy tự tin và hạnh phúc nhất về bản thân?",
"F091$Món ăn mà bạn ghét nhất khi còn nhỏ là gì?",
"F092$Lần đầu tiên bạn bị bố mẹ phạt nặng nhất là vì chuyện gì?",
"F093$Kỷ niệm ngốc nghếch nhất mà bạn còn nhớ khi học cấp 1 là gì?",
"F094$Bạn đã từng ăn trộm thứ gì chưa? Nếu có, đó là thứ gì?",
"F095$Bạn có từng ước mơ trở thành một nghề nghiệp 'bất bình thường' nào không? (ví dụ: người nhặt rác vũ trụ, thám tử chó...)",
"F096$Bài hát 'tủ' mà bạn hay hát thầm khi tắm lúc còn bé là gì?",
"F097$Món đồ chơi mà bạn quý nhất khi còn nhỏ là gì?",
"F098$Bạn đã bao giờ giả vờ ốm để được nghỉ học chưa?",
"F099$Bạn có từng viết thư tình hoặc có 'crush' với ai đó ở trường chưa?",
"F100$Bạn còn giữ lại món đồ nào từ thời thơ ấu đến bây giờ không?",

"E001$Bạn đã bao giờ làm một việc gì đó mà sau này hối hận chưa?",
"E002$Điều bạn ghét nhất ở bản thân là gì?",
"E003$Điều lãng mạn nhất bạn từng làm cho ai đó là gì?",
"E004$Bạn có bao giờ 'lén lút' ăn vụng nửa đêm chưa?",
"E005$Nếu có thể 'đổi' một điều về bản thân, bạn sẽ đổi điều gì?",
"E006$Bạn đã từng 'đặt' tên cho một vật vô tri vô giác chưa?",
"E007$Bạn có từng 'quay cóp' trong thi cử chưa?",
"E008$Nếu có thể thay đổi một điều về ngoại hình, bạn sẽ thay đổi điều gì?",
"E009$Kể về kế hoạch của bạn trong 5 năm tới.",
"E010$Điều gì là mục tiêu lớn nhất bạn muốn đạt được trước tuổi 30?",
"E011$Kể về một lần bạn đã lừa dối ai đó một cách có chủ ý.",
"E012$Nếu bạn chỉ còn một tháng để sống, bạn sẽ làm gì?",
"E013$Điều gì là suy nghĩ bí ẩn nhất mà bạn từng có?",
"E014$Bạn đã bao giờ thử ăn một loại thực phẩm kỳ lạ nào đó chỉ để cho vui chưa?",
"E015$Bạn đã bao giờ thử 'dám' làm một việc gì đó mà sau này phải hối hận chưa?",
"E016$Bạn có từng ăn trộm thứ gì chưa? Nếu có, đó là thứ gì?",
"E017$Bạn có từng 'lục lọi' điện thoại của ai đó chưa?",
"E018$Nếu có thể 'tăng tốc' thời gian khi làm một việc, đó là việc gì?",
"E019$Nếu một ngày bạn thức dậy và có thể nói chuyện với động vật, con vật đầu tiên bạn muốn trò chuyện là gì?",
"E020$Lần đầu tiên bạn bị bố mẹ phạt nặng nhất là vì chuyện gì?",
"E021$Bạn có thể sống thiếu điện thoại trong 1 tháng không?",
"E022$Bạn có thể kể về lần đầu tiên hôn của mình không?",
"E023$Bạn có một thói quen 'ngớ ngẩn' nào khi ở một mình không?",
"E024$Bạn có tin vào tình yêu sét đánh không?",
"E025$Bạn có một 'cách' để 'giấu' cảm xúc của mình không?",
"E026$Bạn có bao giờ 'làm' một điều gì đó vì 'tò mò' không?",
"E027$Bạn nghĩ gì về 'tình yêu' qua mạng xã hội?",
"E028$Nếu không bị giới hạn về tiền bạc, bạn sẽ làm công việc gì?",
"E029$Bạn có tin vào “định mệnh” không?",
"E030$Bạn có muốn kết hôn và có con không?",
"E031$Bạn có một 'tật xấu' nào mà bạn bè không biết không?",
"E032$Bạn còn giữ lại món đồ nào từ thời thơ ấu đến bây giờ không?",
"E033$Bạn có tin vào ma quỷ hay những điều siêu nhiên không?",
"E034$Nếu tiền không phải là vấn đề, bạn sẽ làm gì mỗi ngày?",
"E035$Bạn có một nỗi sợ hãi 'vô lý' nào không?",
"E036$Món quà 'vô dụng' nhất mà bạn từng nhận được là gì?",
"E037$Lần cuối cùng bạn khóc là khi nào và vì sao?",
"E038$Lần cuối cùng bạn khóc là vì chuyện gì?",
"E039$Điều bạn 'hối hận' nhất khi còn đi học là gì?",
"E040$Nếu được chọn một nghề nghiệp khác, bạn muốn làm gì?",
"E041$Kể về một kỷ niệm đáng nhớ nhất thời đi học.",
"E042$Điều gì là áp lực lớn nhất của bạn trong công việc/học tập hiện tại?",
"E043$Nếu có thể biến một thứ bất kỳ thành món tráng miệng, bạn sẽ chọn cái gì?",
"E044$Nếu được chọn một siêu năng lực, bạn sẽ chọn gì và dùng nó để làm gì?",
"E045$Kỷ niệm ngốc nghếch nhất mà bạn còn nhớ khi học cấp 1 là gì?",
"E046$Nếu có thể thay đổi một điều trong quá khứ, bạn sẽ thay đổi điều gì?",
"E047$Nếu có thể 'tẩy não' một kỷ niệm trong quá khứ, bạn sẽ xóa đi kỷ niệm nào?",
"E048$Kể về một kỷ niệm thời thơ ấu khiến bạn cảm thấy bị ám ảnh đến bây giờ.",
"E049$Điều gì khiến bạn cảm thấy 'tội lỗi' nhất khi làm điều gì?",
"E050$Điều gì khiến bạn cảm thấy tự tin và hạnh phúc nhất về bản thân?",
"E051$Bạn có bao giờ lén lút đọc tin nhắn của người khác chưa?",
"E052$Ai là người bạn tin tưởng nhất trên đời?",
"E053$Bạn có bao giờ 'ăn trộm' đồ ăn của người khác chưa?",
"E054$Nếu bạn có thể thay đổi cách mọi người nhìn nhận bạn, bạn sẽ thay đổi điều gì?",
"E055$Bạn sẽ làm gì nếu bạn đột nhiên trở thành người duy nhất trên Trái Đất?",
"E056$Bạn có bao giờ cảm thấy mình là một gánh nặng cho gia đình không?",
"E057$Điều gì khiến bạn cảm thấy mình không xứng đáng với tình yêu/hạnh phúc?",
"E058$Bạn có tin rằng con người về bản chất là tốt hay xấu không?",
"E059$Bạn có bao giờ giả vờ ốm để được nghỉ học/nghỉ làm chưa?",
"E060$Bạn đã bao giờ giả vờ ốm để được nghỉ học chưa?",
"E061$Bạn thích tắm vòi sen hay tắm bồn hơn?",
"E062$Bạn thích nhận quà bất ngờ hay được hỏi trước khi mua hơn?",
"E063$Bí mật nào bạn chưa từng kể với ai trong nhóm?",
"E064$Bạn có bao giờ ghen tị với ai đó chưa?",
"E065$Bạn có một bí mật nào đó mà bạn chưa từng kể cho ai không?",
"E066$Bạn có một 'bí mật' nào đó về gia đình bạn mà bạn chưa từng kể cho ai không?",
"E067$Lần bạn 'quê độ' nhất trước mặt người lạ là khi nào?",
"E068$Bạn đã bao giờ phải lòng một nhân vật hư cấu chưa?",
"E069$Bạn sẽ làm gì nếu phát hiện bạn thân đang nói xấu mình?",
"E070$Bạn có một 'nguyên tắc' sống nào không bao giờ phá vỡ không?",
"E071$Bạn đã bao giờ nói dối rằng mình đã xem một bộ phim hoặc một cuốn sách nào đó để 'hợp' với mọi người chưa?",
"E072$Bạn đã từng làm điều gì 'ngu ngốc' nhất để gây ấn tượng với người khác?",
"E073$Kể về lần đầu tiên bạn gặp người bạn thân nhất của mình.",
"E074$Điều gì ở một người bạn khiến bạn khó chịu nhất nhưng bạn vẫn chấp nhận được?",
"E075$Bạn có nghĩ mình là một người tốt không?",
"E076$Lần cuối cùng bạn 'khóc' vì một người khác là khi nào?",
"E077$Nếu có một người theo dõi bạn cả ngày và ghi lại mọi việc bạn làm, họ sẽ thấy điều gì bất ngờ nhất?",
"E078$Nếu phải bị mắc kẹt ở một hòn đảo hoang với một người nào đó, bạn sẽ chọn ai trong nhóm chúng ta?",
"E079$Bạn có bao giờ 'tưởng tượng' mình là một người khác không?",
"E080$Nếu có thể trở lại quá khứ để thay đổi một điều về mối quan hệ của bạn với một người nào đó, bạn sẽ thay đổi điều gì?",
"E081$Nếu bạn biết một người thân của bạn đã phạm một tội ác nghiêm trọng, bạn có tố giác họ không?",
"E082$Điều gì bạn cảm thấy đáng sợ nhất ở người bạn thân nhất của mình?",
"E070$Bạn có một 'nguyên tắc' sống nào không bao giờ phá vỡ không?",
"E071$Bạn đã bao giờ nói dối rằng mình đã xem một bộ phim hoặc một cuốn sách nào đó để 'hợp' với mọi người chưa?",
"E072$Bạn đã từng làm điều gì 'ngu ngốc' nhất để gây ấn tượng với người khác?",
"E073$Kể về lần đầu tiên bạn gặp người bạn thân nhất của mình.",
"E074$Điều gì ở một người bạn khiến bạn khó chịu nhất nhưng bạn vẫn chấp nhận được?",
"E075$Bạn có nghĩ mình là một người tốt không?",
"E076$Lần cuối cùng bạn 'khóc' vì một người khác là khi nào?",
"E077$Nếu có một người theo dõi bạn cả ngày và ghi lại mọi việc bạn làm, họ sẽ thấy điều gì bất ngờ nhất?",
"E078$Nếu phải bị mắc kẹt ở một hòn đảo hoang với một người nào đó, bạn sẽ chọn ai trong nhóm chúng ta?",
"E079$Bạn có bao giờ 'tưởng tượng' mình là một người khác không?",
"E080$Nếu có thể trở lại quá khứ để thay đổi một điều về mối quan hệ của bạn với một người nào đó, bạn sẽ thay đổi điều gì?",
"E081$Nếu bạn biết một người thân của bạn đã phạm một tội ác nghiêm trọng, bạn có tố giác họ không?",
"E082$Điều gì bạn cảm thấy đáng sợ nhất ở người bạn thân nhất của mình?",
"E083$Kể về một kỷ niệm xấu hổ nhất của bạn và người bạn thân.",
"E073$Kể về lần đầu tiên bạn gặp người bạn thân nhất của mình.",
"E074$Điều gì ở một người bạn khiến bạn khó chịu nhất nhưng bạn vẫn chấp nhận được?",
"E075$Bạn có nghĩ mình là một người tốt không?",
"E076$Lần cuối cùng bạn 'khóc' vì một người khác là khi nào?",
"E077$Nếu có một người theo dõi bạn cả ngày và ghi lại mọi việc bạn làm, họ sẽ thấy điều gì bất ngờ nhất?",
"E078$Nếu phải bị mắc kẹt ở một hòn đảo hoang với một người nào đó, bạn sẽ chọn ai trong nhóm chúng ta?",
"E079$Bạn có bao giờ 'tưởng tượng' mình là một người khác không?",
"E080$Nếu có thể trở lại quá khứ để thay đổi một điều về mối quan hệ của bạn với một người nào đó, bạn sẽ thay đổi điều gì?",
"E081$Nếu bạn biết một người thân của bạn đã phạm một tội ác nghiêm trọng, bạn có tố giác họ không?",
"E082$Điều gì bạn cảm thấy đáng sợ nhất ở người bạn thân nhất của mình?",
"E078$Nếu phải bị mắc kẹt ở một hòn đảo hoang với một người nào đó, bạn sẽ chọn ai trong nhóm chúng ta?",
"E079$Bạn có bao giờ 'tưởng tượng' mình là một người khác không?",
"E080$Nếu có thể trở lại quá khứ để thay đổi một điều về mối quan hệ của bạn với một người nào đó, bạn sẽ thay đổi điều gì?",
"E081$Nếu bạn biết một người thân của bạn đã phạm một tội ác nghiêm trọng, bạn có tố giác họ không?",
"E082$Điều gì bạn cảm thấy đáng sợ nhất ở người bạn thân nhất của mình?",
"E080$Nếu có thể trở lại quá khứ để thay đổi một điều về mối quan hệ của bạn với một người nào đó, bạn sẽ thay đổi điều gì?",
"E081$Nếu bạn biết một người thân của bạn đã phạm một tội ác nghiêm trọng, bạn có tố giác họ không?",
"E082$Điều gì bạn cảm thấy đáng sợ nhất ở người bạn thân nhất của mình?",
"E081$Nếu bạn biết một người thân của bạn đã phạm một tội ác nghiêm trọng, bạn có tố giác họ không?",
"E082$Điều gì bạn cảm thấy đáng sợ nhất ở người bạn thân nhất của mình?",
"E083$Kể về một kỷ niệm xấu hổ nhất của bạn và người bạn thân.",
"E084$Bạn có từng 'phản bội' một người bạn thân chưa?",
"E085$Bạn có sẵn sàng tha thứ cho một người bạn đã phản bội mình không?",
"E082$Điều gì bạn cảm thấy đáng sợ nhất ở người bạn thân nhất của mình?",
"E083$Kể về một kỷ niệm xấu hổ nhất của bạn và người bạn thân.",
"E084$Bạn có từng 'phản bội' một người bạn thân chưa?",
"E085$Bạn có sẵn sàng tha thứ cho một người bạn đã phản bội mình không?",
"E083$Kể về một kỷ niệm xấu hổ nhất của bạn và người bạn thân.",
"E084$Bạn có từng 'phản bội' một người bạn thân chưa?",
"E085$Bạn có sẵn sàng tha thứ cho một người bạn đã phản bội mình không?",
"E084$Bạn có từng 'phản bội' một người bạn thân chưa?",
"E085$Bạn có sẵn sàng tha thứ cho một người bạn đã phản bội mình không?",
"E086$Bạn đã bao giờ nói 'tôi yêu bạn' với một người bạn thân chưa?",
"E087$Bạn đã từng 'crush' người yêu của bạn thân chưa?",
"E088$Bạn đã bao giờ 'thích' một người vì tính cách 'ngược ngạo' của họ chưa?",
"E089$Có điều gì bạn không thích ở một người bạn thân nhưng chưa bao giờ nói ra không?",
"E090$Bạn đã bao giờ phải lòng một người bạn thân chưa?",

"D001$Bạn có bao giờ bịa chuyện về một ai đó để được nổi tiếng chưa?",
"D002$Bạn đã từng bị say xỉn và làm một việc gì đó điên rồ chưa?",
"D003$Bạn nghĩ gì về việc 'ngoại tình'?",
"D004$Bạn đã từng gửi nhầm tin nhắn 'nhạy cảm' chưa?",
"D005$Bạn có bao giờ 'nói xấu' bạn bè của mình chưa?",
"D006$Lần bạn 'phạm' một điều luật 'quan trọng' là khi nào?",
"D007$Nếu được 'đổi' một điều về cuộc đời mình, bạn sẽ đổi điều gì?",
"D008$Bạn đã từng 'bị' lừa đảo qua mạng xã hội chưa?",
"D009$Nếu bạn chỉ còn một ngày để sống, bạn sẽ làm gì?",
"D010$Điều gì khiến bạn sợ hãi nhất?",
"D011$Kể về lần gần nhất bạn ăn trộm hoặc lấy cắp một thứ gì đó.",
"D012$Nếu có một siêu năng lực, bạn muốn có siêu năng lực gì?",
"D013$Kể về một lần bạn bị mất mặt ở nơi công cộng.",
"D014$Nếu phải sống trên một hoang đảo, bạn muốn mang theo 3 thứ gì?",
"D015$Điều gì là ước mơ điên rồ nhất bạn chưa bao giờ dám nói ra?",
"D016$Kể về một lần bạn bị áp lực phải làm điều gì đó trái với đạo đức bản thân.",
"D017$Nếu thần đèn ban cho bạn ba điều ước, bạn sẽ cầu xin điều gì và tại sao?", 
"D018$Bạn đã bao giờ phớt lờ ai đó chưa?",
"D019$Nỗi đau thể xác tồi tệ nhất mà bạn từng trải qua là gì?",
"D020$Nếu có thể thay đổi một điều về bản thân bạn chỉ trong 24 giờ, bạn sẽ thay đổi điều gì và tại sao?",
"D021$Bạn đã bao giờ 'đánh cắp' một món đồ nhỏ nào đó chỉ vì muốn sở hữu nó chưa?",
"D022$Bạn đã từng 'phản bội' lòng tin của ai đó chưa?",
"D023$Bạn có từng viết một lá thư tình hoặc một bài thơ cho ai đó chưa?",
"D024$Bạn có từng 'lục lọi' điện thoại của ai đó chưa?",
"D025$Nếu một ngày bạn thức dậy và có thể nói chuyện với động vật, con vật đầu tiên bạn muốn trò chuyện là gì?",
"D026$Bạn đã bao giờ 'lén lút' đi chơi ở một nơi mà bố mẹ bạn cấm chưa?",
"D027$Bạn có một nỗi sợ hãi nào 'kỳ cục' không?",
"D028$Bạn có thể kể về lần đầu tiên 'tò mò' về giới tính không?",
"D029$Bạn có một thói quen 'kỳ lạ' nào liên quan đến giấc ngủ không?",
"D030$Bạn nghĩ gì về 'tình yêu' qua 'tình một đêm'?",
"D031$Bạn tin vào ma quỷ hay thế giới tâm linh không?",
"D032$Bạn có tin tưởng ai trong nhóm này tuyệt đối không? Nếu không, tại sao?",
"D033$Bạn có từng nghĩ đến việc 'bỏ trốn' khỏi nhà không?",
"D034$Bạn có bao giờ tự hỏi liệu cuộc sống của bạn có thật sự 'tốt' như bạn vẫn thể hiện ra không?",
"D035$Bạn có một nỗi sợ hãi 'vô lý' nào không?",
"D036$Nếu tiền không phải là vấn đề, bạn sẽ làm gì mỗi ngày?",
"D037$Bạn có một 'tật xấu' nào mà bạn bè không biết không?",
"D038$Bạn có tin vào ma quỷ hay những điều siêu nhiên không?",
"D039$Bạn nghĩ 'tình yêu sét đánh' có thật không?",
"D040$Bạn có từng 'ăn cắp' bản quyền của ai đó chưa?",
"D041$Bạn đã bao giờ khóc vì một cuốn sách/bộ phim chưa?",
"D042$Lần cuối cùng bạn khóc là vì chuyện gì?",
"D043$Nếu có thể biến một thứ bất kỳ thành món tráng miệng, bạn sẽ chọn cái gì?",
"D044$Nếu bạn có thể 'tẩy não' một kỷ niệm trong quá khứ, bạn sẽ xóa đi kỷ niệm nào?",
"D045$Điều gì khiến bạn cảm thấy hối tiếc nhất trong cuộc đời?",
"D046$Điều gì khiến bạn cảm thấy 'tội lỗi' nhất khi làm điều gì?",
"D047$Điều gì khiến bạn cảm thấy tự tin và hạnh phúc nhất về bản thân?",
"D048$Điều gì khiến bạn cảm thấy an toàn và thoải mái khi ở bên cạnh ai đó?",
"D049$Bạn đã từng 'thả thính' cùng lúc nhiều người chưa?",
"D050$Bạn có từng giả vờ mình là người khác trên mạng xã hội chưa?",
"D051$Bạn có bao giờ 'lén lút' nghe lén cuộc trò chuyện của người khác chưa?",
"D052$Nếu bạn đột nhiên trở thành người duy nhất trên Trái Đất, bạn sẽ làm gì?",
"D053$Điều gì ở người khác mà bạn ngưỡng mộ nhất?",
"D054$Bạn đã bao giờ lừa dối người yêu chưa?",
"D055$Bạn có một 'cách' để 'được lòng' người khác không?",
"D056$Bạn có từng 'phá hoại' một mối quan hệ của người khác không?",
"D057$Bạn có từng 'sáng tác' ra một câu chuyện hoặc một lời nói dối chỉ để thoát khỏi rắc rối chưa?",
"D058$Người chơi nào sẽ sống sót sau thảm họa zombie và ai sẽ là người đầu tiên ra đi?",
"D059$Nếu bạn chỉ được xem phim hài lãng mạn hoặc phim kinh dị trong suốt quãng đời còn lại, bạn sẽ chọn phim nào và tại sao?",
"D060$Bí mật nào bạn chưa từng kể với ai trong nhóm?",
"D061$Bạn có một sở thích nào 'kỳ lạ' không?",
"D062$Nếu được chọn, bạn muốn làm người yêu của ai trong nhóm này?",
"D063$Bạn có từng 'bắt nạt' một ai đó mà bạn không thích chưa?",
"D064$Lần bạn làm 'quê' người khác trước mặt đám đông là khi nào?",
"D065$Bạn đã bao giờ phải lòng một nhân vật hư cấu chưa?",
"D066$Điều gì khiến bạn cảm thấy bị cô lập hoặc lạc lõng trong một nhóm đông người?",
"D067$Bạn có tin vào lời nguyền không?",
"D068$Bạn có một 'nguyên tắc' nào về tình yêu không bao giờ phá vỡ không?",
"D069$Bạn đã bao giờ nói dối rằng mình đã xem một bộ phim hoặc một cuốn sách nào đó để 'hợp' với mọi người chưa?",
"D070$Lần đầu tiên bạn bị 'thất tình' là khi nào?",
"D071$Bạn có một bí mật 'lớn' nào về người yêu cũ của bạn không?",
"D072$Bạn có ghen tị với thành công của người khác không?",
"D073$Bạn có một sở thích 'đặc biệt' nào mà bạn không muốn ai biết không?",
"D074$Bạn đã từng 'dụ dỗ' một người nào đó để đạt được mục đích của mình chưa?",
"D075$Điều gì ở một người bạn khiến bạn khó chịu nhất nhưng bạn vẫn chấp nhận được?",
"D076$Điều gì bạn nghĩ là tệ' nhất khi bạn có một người bạn trai/bạn gái?",
"D077$Món quà ý nghĩa nhất bạn từng nhận được từ một người bạn là gì?",
"D078$Nếu có thể cho một người bạn bất kỳ một lời khuyên, bạn sẽ nói gì?",
"D079$Bạn có thể mô tả một người bạn 'hoàn hảo' là như thế nào không?",
"D080$Bạn có bao giờ 'nói xấu' một người nào đó ngay trước mặt họ chưa?",
"D081$Nếu phải bị mắc kẹt ở một hòn đảo hoang với một người nào đó, bạn sẽ chọn ai trong nhóm chúng ta?",
"D082$Bạn có bao giờ 'tưởng tượng' mình là một người 'tồi tệ' không?",
"D083$Bạn có từng nói dối bạn bè để được đi chơi với người bạn thích chưa?",
"D084$Nếu có thể trở lại quá khứ để thay đổi một điều về mối quan hệ của bạn với một người nào đó, bạn sẽ thay đổi điều gì?",
"D085$Bạn đã bao giờ cảm thấy 'thất vọng' về một người bạn chưa?",
"D086$Nếu bạn biết được một bí mật đen tối của một người bạn, bạn sẽ nói ra hay giữ im lặng?",
"D087$Bạn có thích một người đã có người yêu chưa?",
"D088$Lần cuối cùng bạn 'ghen' với một người khác là khi nào?",
"D089$Bạn đã bao giờ phải lòng một người đã có người yêu chưa?",
"D090$Bạn có bao giờ 'thích' một người mà bạn biết họ có 'vấn đề' chưa?",
"D091$Bạn có bao giờ nói xấu sau lưng một người bạn thân chưa?",
"D092$Bạn đã từng 'để ý' đến một người bạn thân chưa?",
"D093$Bạn đã bao giờ nói tôi yêu bạn' với một người bạn thân chưa?",
"D094$Bạn có thể kể một kỷ niệm đáng nhớ với một người bạn thân mà bạn không muốn ai biết không?",
"D095$Bạn đã từng 'chia sẻ' bí mật của một người bạn với người khác chưa?",
"D096$Bạn đã bao giờ cảm thấy ghen tị với một người bạn chưa?",
"D097$Bạn có một 'bí mật' nào với một người bạn thân mà bạn không muốn ai biết không?",
"D098$Bạn đã bao giờ 'thích' một người vì 'gu' thời trang của họ chưa?",
"D099$Điều gì bạn nghĩ là 'tệ' nhất khi bạn có một người bạn thân khác giới?",
"D100$Bạn đã từng làm điều gì táo bạo nhất để 'hạ gục' một người bạn đã 'crush'?",

"C001$Bạn đã từng làm 'chuyện ấy' với ai chưa?",
"C002$Bạn có bao giờ dùng 'sextoys' chưa?",
"C003$Bạn có bao giờ 'thủ dâm' ở nơi công cộng chưa?",
"C004$Bạn đã từng quay 'clip' nhạy cảm chưa?",
"C005$Bạn có bao giờ xem 'phim đen' chưa?",
"C006$Lần bạn 'phạm' một điều luật 'quan trọng' là khi nào?",
"C007$Nếu được 'đổi' một điều về cuộc đời mình, bạn sẽ đổi điều gì?",
"C008$Bạn đã từng 'bị' lừa đảo qua mạng xã hội chưa?",
"C009$Bạn có bao giờ bị “bắt cá hai tay” hoặc 'cắm sừng' chưa?",
"C010$Nếu có thể xóa một kỷ niệm xấu ra khỏi bộ nhớ, bạn sẽ xóa điều gì?",
"C011$Nơi kỳ lạ nhất mà bạn từng đi vệ sinh là ở đâu?",
"C012$Bạn đã bao giờ 'bị từ chối' một cách 'đau lòng' chưa?",
"C013$Bạn nghĩ điều gì là quan trọng nhất trong một mối quan hệ?",
"C014$Bạn nghĩ 'chia tay' một cách tốt nhất là như thế nào?",
"C015$Bạn nghĩ gì về tình yêu 'một đêm'?",
"C016$Bạn có một 'ám ảnh' nào đó về tình dục không?",
"C017$Bạn có bao giờ bị 'đánh cắp' một nụ hôn chưa?",
"C018$Bạn có thể kể về lần đầu tiên 'quan hệ' của mình không?",
"C019$Bạn có nghĩ 'tình dục' là điều quan trọng trong tình yêu không?",
"C020$Bạn có một thói quen 'kỳ lạ' nào liên quan đến tình yêu không?",
"C021$Bạn nghĩ gì về 'tình yêu' qua 'tình một đêm'?",
"C022$Kể về lần đầu tiên bạn biết yêu.",
"C023$Bạn có từng tự làm tổn thương bản thân không? (Về cả thể chất và tinh thần)",
"C024$Bạn có tin vào “karma” (luật nhân quả) không?",
"C025$Bạn có sợ cái chết không? Vì sao?",
"C026$Bạn nghĩ 'tình yêu đích thực' là gì?",
"C027$Bạn đã bao giờ làm một điều gì 'điên rồ' chỉ vì tình yêu chưa?",
"C028$Lần cuối cùng bạn khóc là khi nào và vì sao?",
"C029$Bạn có từng bị 'bắt nạt' (bắt nạt học đường, bắt nạt công sở...) chưa? Kể về trải nghiệm đó.",
"C030$Nếu có thể đổi chỗ cho một cặp đôi nổi tiếng, bạn sẽ chọn ai?",
"C031$Nếu có thể quay lại quá khứ, bạn sẽ thay đổi điều gì trong một mối quan hệ đã kết thúc?",
"C032$Nếu phải chọn, bạn sẽ chọn tình yêu hay sự nghiệp?",
"C033$Điều gì bạn cảm thấy nuối tiếc nhất trong cuộc đời?",
"C034$Bạn có bao giờ 'lén lút' nghe lén cuộc trò chuyện của người khác chưa?",
"C035$Bạn đã từng có ý nghĩ 'ngoài luồng' với người yêu của bạn chưa?",
"C036$Bạn có một 'cách' để 'được lòng' người khác không?",
"C037$Bạn đã bao giờ lén kiểm tra điện thoại của người yêu chưa?",
"C038$Điều điên rồ nhất bạn từng làm cho người mình yêu là gì?",
"C039$Kể về lần bạn nói dối cha mẹ một chuyện lớn.",
"C040$Điều gì khiến bạn thấy xấu hổ nhất về bản thân?",
"C041$Bạn thích 'hẹn hò' truyền thống hay 'hẹn hò' hiện đại hơn?",
"C042$Bí mật đen tối nhất mà bạn chưa từng tiết lộ cho ai là gì?",
"C043$Điều gì khiến bạn ghen tuông nhất trong một mối quan hệ?",
"C044$Bạn có một bí mật 'đen tối' nào chưa từng kể cho ai không?",
"C045$Bạn có một bí mật tình cảm nào mà bạn chưa từng kể với ai không?",
"C046$Bạn đã bao giờ phải lòng một nhân vật hư cấu trong phim hoặc sách chưa?",
"C047$Bạn đã bao giờ có tình cảm với bạn thân của mình chưa?",
"C048$Bạn có tin vào lời nguyền không?",
"C049$Bạn có một 'nguyên tắc' nào về tình yêu không bao giờ phá vỡ không?",
"C050$Kể một lần bạn bị “friend-zone” hoặc “crush” từ chối.",
"C051$Mối tình 'crush' đầu tiên của bạn là với ai?",
"C052$Bạn thích người bạn đời lý tưởng của mình có 3 điểm gì?",
"C053$Bạn đã từng 'sáng tác' một bài hát hoặc một bài thơ cho người bạn thích chưa?",
"C054$Bạn có bao giờ 'tự sướng' chưa?",
"C055$Bạn đã bao giờ 'lén lút' đi chơi với người bạn thích mà không cho ai biết chưa?",
"C056$Bạn có một bí mật 'lớn' nào về người yêu cũ của bạn không?",
"C057$Bạn đã từng ngủ với một người lạ chưa?",
"C058$Điều gì ở một người khiến bạn 'rung động' ngay từ lần gặp đầu tiên?",
"C059$Bạn thích 'yêu thầm' hay 'yêu công khai' hơn?",
"C060$Lần bạn 'thất tình' mà bạn cảm thấy đau khổ nhất là khi nào?",
"C061$Bạn có bao giờ 'nói xấu' một người nào đó ngay trước mặt họ chưa?",
"C062$Bạn có bao giờ 'tưởng tượng' mình là một người 'tồi tệ' không?",
"C063$Bạn có bao giờ 'lên giường' với bạn thân của mình chưa?",
"C064$Lần cuối cùng bạn 'ghen' với một người khác là khi nào?",
"C065$Bạn có thể kể một kỷ niệm đáng nhớ với một người bạn thích mà bạn không muốn ai biết không?",
"C066$Bạn có bao giờ phải lòng một người đã có chủ chưa?",
"C067$Bạn đã từng 'phải lòng' một người đã có người yêu chưa?",
"C068$Bạn có bao giờ 'thích' một người mà bạn biết họ có 'vấn đề' chưa?",
"C069$Bạn đã bao giờ 'để ý' đến một người bạn thân chưa?",
"C070$Bạn đã bao giờ 'thích' một người vì 'gu' âm nhạc của họ chưa?",

"B001$Bạn đã từng 'tự tử' chưa?",
"B002$Bạn đã từng 'đánh cắp' một vật gì đó có giá trị lớn chưa?",
"B003$Bạn có bao giờ 'cực đoan' trong tình dục chưa?",
"B004$Bạn có thể kể về lần 'bị lạm dụng' chưa?",
"B005$Bạn có bao giờ 'bán dâm' chưa?",
"B006$Bạn có bao giờ 'cưỡng hiếp' ai đó chưa?",
"B007$Lần bạn 'phạm' một điều luật 'quan trọng' là khi nào?",
"B008$Nếu được 'đổi' một điều về cuộc đời mình, bạn sẽ đổi điều gì?",
"B009$Bạn đã từng 'bị' lừa đảo qua mạng xã hội chưa?",
"B010$Lần cuối cùng bạn đi vệ sinh ở một nơi “kỳ lạ” là khi nào?",
"B011$Kể về lần đầu tiên bạn thử hút thuốc (nếu có).",
"B012$Bạn đã bao giờ ăn trộm thứ gì chưa? Nếu có, đó là thứ gì?",
"B013$Nếu có thể thay đổi một điều về bản thân bạn chỉ trong 24 giờ, bạn sẽ thay đổi điều gì và tại sao?",
"B014$Bạn có từng 'phản bội' lòng tin của ai đó chưa?",
"B015$Bạn có một 'khao khát' tình dục kỳ lạ nào không?",
"B016$Bạn có một thói quen 'kỳ lạ' nào liên quan đến tình yêu không?",
"B017$Bạn nghĩ gì về 'tình yêu' qua 'tình một đêm'?",
"B018$Bạn có bao giờ tự hỏi liệu cuộc sống của bạn có thật sự 'tốt' như bạn vẫn thể hiện ra không?",
"B019$Bạn có một nỗi sợ hãi 'vô lý' nào không?",
"B020$Bạn đã từng 'ăn cắp' tiền của bố mẹ chưa?",
"B021$Bạn đã bao giờ giả vờ bị ốm để trốn việc/trốn học chưa?",
"B022$Nếu có thể biến một thứ bất kỳ thành món tráng miệng, bạn sẽ chọn cái gì?",
"B023$Nếu có thể 'tẩy não' một kỷ niệm trong quá khứ, bạn sẽ xóa đi kỷ niệm nào?",
"B024$Bạn có một 'khuất tất' nào đó về quá khứ không?",
"B025$Bạn đã từng 'phá hoại' một mối quan hệ nào đó của người khác chưa?",
"B026$Bạn có bao giờ 'quan hệ' với người cùng giới chưa?",
"B027$Bạn đã từng 'quan hệ' với người 'có quan hệ' với bạn bè của bạn chưa?",
"B028$Bạn có bao giờ 'tống tiền' người khác chưa?",
"B029$Bạn có bao giờ 'lén lút' nghe lén cuộc trò chuyện của người khác chưa?",
"B030$Nếu bạn đột nhiên trở thành người duy nhất trên Trái Đất, bạn sẽ làm gì?",
"B031$Bạn có một 'cách' để 'được lòng' người khác không?",
"B032$Bí mật nào bạn chưa từng kể với ai trong nhóm?",
"B033$Bạn có một 'bí mật' nào đó liên quan đến pháp luật không?",
"B034$Lần bạn làm 'quê' người khác trước mặt đám đông là khi nào?",
"B035$Bạn đã bao giờ phải lòng một nhân vật hư cấu trong phim hoặc sách chưa?",
"B036$Kể về một lần bạn làm một điều gì đó ngu ngốc chỉ vì bị thách đố.",
"B037$Bạn có tin vào lời nguyền không?",
"B038$Bạn có một 'nguyên tắc' nào về tình yêu không bao giờ phá vỡ không?",
"B039$Bạn có một bí mật 'lớn' nào về người yêu cũ của bạn không?",
"B040$Bạn có một sở thích 'đặc biệt' nào mà bạn không muốn ai biết không?",
"B041$Bạn có bao giờ 'tấn công' một người nào đó chưa?",
"B042$Bạn có bao giờ 'nói xấu' một người nào đó ngay trước mặt họ chưa?",
"B043$Nếu có thể đổi chỗ cho một người khác trong một ngày, bạn sẽ chọn ai?",
"B044$Bạn có bao giờ 'tưởng tượng' mình là một người 'tồi tệ' không?",
"B045$Bạn có từng nói dối bạn bè để được đi chơi với người bạn thích chưa?",
"B046$Bạn đã từng làm điều gì điên rồ nhất để gây ấn tượng với một người bạn thích?",
"B047$Lần cuối cùng bạn 'ghen' với một người khác là khi nào?",
"B048$Bạn đã bao giờ phải lòng một người đã có người yêu chưa?",
"B049$Bạn có bao giờ 'thích' một người mà bạn biết họ có 'vấn đề' chưa?",
"B050$Bạn đã bao giờ 'thích' một người vì 'gu' âm nhạc của họ chưa?",

"A001$Món đồ lót màu gì bạn thấy 'sexy' nhất?",
"A002$Lần cuối cùng bạn 'thèm khát' ai đó là khi nào?",
"A003$Nếu được tặng một bộ đồ ngủ, bạn muốn nó 'thiếu vải' hay 'kín đáo'?",
"A004$Đâu là điều 'tồi tệ' nhất bạn đã làm trong một mối quan hệ?",
"A005$Lần bạn 'phạm' một điều luật 'quan trọng' là khi nào?",
"A006$Nếu được 'đổi' một điều về cuộc đời mình, bạn sẽ đổi điều gì?",
"A007$Bạn đã từng 'bị' lừa đảo qua mạng xã hội chưa?",
"A008$Bạn đã bao giờ nghĩ đến chuyện ngoại tình chưa? Nếu có, vì sao?",
"A009$Bạn nghĩ nụ hôn ở đâu trên cơ thể là 'điên' nhất?",
"A010$Bạn có nghĩ mình 'hấp dẫn' không?",
"A011$Bạn có một thói quen 'kỳ lạ' nào liên quan đến tình yêu không?",
"A012$Bạn nghĩ gì về 'tình yêu' qua 'tình một đêm'?",
"A013$Kể về một lần bạn bị tổn thương sâu sắc trong tình yêu.",
"A014$Kể về lần đầu tiên bạn hôn ai đó.",
"A015$Bạn đã bao giờ “yêu” ai đó mà họ lại không yêu bạn chưa? Kể về cảm xúc lúc đó.",
"A016$Bạn có bao giờ 'lén lút' nghe lén cuộc trò chuyện của người khác chưa?",
"A017$Điều gì ở người bạn đời cũ khiến bạn nhớ nhất (về cả mặt cảm xúc lẫn thể xác)?",
"A018$Bạn có một 'cách' để quyến rũ người khác không?",
"A019$Bạn nghĩ mình có thể 'chiều' người yêu đến mức nào?",
"A020$Bạn có một 'cách' để 'được lòng' người khác không?",
"A021$Bạn có từng 'thao túng tâm lý' (manipulate) người yêu để đạt được điều mình muốn không?",
"A022$Bạn có 'ám ảnh' với người yêu cũ không? Nếu có, vì sao?",
"A023$Bạn sẽ phản ứng thế nào nếu người yêu bạn yêu cả hai giới?",
"A024$Bạn thích được 'vuốt ve' ở đâu nhất?",
"A025$Bạn thích được 'thủ thỉ' điều gì vào tai?",
"A026$Bạn có một 'bí mật' nào đó về tình dục mà bạn chưa kể cho ai không?",
"A027$Bạn có tin vào lời nguyền không?",
"A028$Bạn có một 'nguyên tắc' nào về tình yêu không bao giờ phá vỡ không?",
"A029$Bạn có bao giờ cảm thấy thiếu tự tin về cơ thể của mình trước người yêu/bạn tình chưa?",
"A030$Đâu là vị trí 'thích' của bạn khi ngủ cùng người ấy?",
"A031$Bạn có một bí mật 'lớn' nào về người yêu cũ của bạn không?",
"A032$Bạn có 'khao khát' được hôn một người nào đó trong nhóm này không?",
"A033$Bạn có nghĩ mình là một người 'tốt' trên giường không?",
"A034$Bạn có bao giờ 'nói xấu' một người nào đó ngay trước mặt họ chưa?",
"A035$Bạn có bao giờ 'tưởng tượng' mình là một người 'tồi tệ' không?",
"A036$Lần cuối cùng bạn 'ghen' với một người khác là khi nào?",
"A037$Bạn đã bao giờ 'thích' một người vì mùi hương cơ thể của họ chưa?",
"A038$Bạn có bao giờ 'thích' một người mà bạn biết họ có 'vấn đề' chưa?",
"A039$Cảm giác yêu thầm một người bạn thân là như thế nào?",
"A040$Bạn đã bao giờ 'thích' một người vì 'gu' âm nhạc của họ chưa?",

"SX.X$Màu áo lót mà bạn đang mặc?---Nam miễn!!!",
"SX.X$Bạn đã bao giờ tò mò về tinh dịch của bản thân có vị gì chưa?!!!",
"SX.X$Nếu bắt buộc lựa chọn, bạn sẽ chọn làm BedBoy hay BadBoy?!!!",
"SX.X$Vào đêm cặp đôi của bạn, bạn sẽ lựa chọn không gian thoáng hay trong phòng?!!!",
"SX.X$Tên người mà bạn mơ thấy khi mộng tinh?!!!",
"SX.X$Bạn có nghĩ mình là người hôn giỏi không?!!!",
"SX.X$Bạn có cảm giác thèm khát ôm crush từ đằng sau dù chẳng là gì chưa?---Nữ miễn!!!",
"SX.X$Đối với bạn, ham muốn sẽ đứng thứ mấy trong một mối quan hệ đẫ và đang trải qua?!!!",
"SX.X$Bạn cảm nhận chỗ đó của bạn có mùi như thế nào?---Nam miễn!!!",
"SX.X$Bạn thấy phần lông chỗ đó của bạn như nào?---Nữ miễn!!!",
"SX.X$Bạn muốn cùng ai trong nhóm này xem phim heo?!!!",
"SX.X$Cây hàng của bạn dài bao nhiêu?---Nữ miễn!!!",
"SX.X$Cảm giác hôn môi một người yêu như thế nào?!!!",
"SX.X$Bạn bắt đầu cảm thấy muốn làm chuyện đó với người mình thích vào năm nào?!!!",
"SX.X$Loại đồ ngủ mà bạn cảm thấy thú thú nhất khi người yêu hoặc crush mình mặc?!!!",
"SX.X$Bạn có cạo lông chỗ đó không?---Nam miễn!!!",
]